### ISSUE TITLE
Dependency not satisified https://github.com/bghira/optimum-quanto-simpletuner

### ISSUE THREAD

**Issue by hexlivelive** [bghira/SimpleTuner#1009]
This repo https://github.com/bghira/optimum-quanto-simpletuner seems to have gone away. "poetry install" fails

**Comment by bghira** [comment]
the main branch has the fix for this, and if you could use that branch, we will get closer to merging it into release (assuming no issues, or that we resolve any issues you discover on main)

**Comment by bghira** [comment]
alternatively, i've pushed the updated dependency lists to the main branch.
