### ISSUE TITLE
Configuration script does not work

### ISSUE THREAD

**Issue by kopyl** [bghira/SimpleTuner#1024]
https://github.com/bghira/SimpleTuner/blob/6c8420d2a04ccaa2e164fc23e0b00efe2cf23af7/documentation/quickstart/FLUX.md?plain=1#L102C25-L102C39

Unless i run `pip install --upgrade torch` beforehand.

**Comment by bghira** [comment]
you skipped every step before it?

**Comment by kopyl** [comment]
> you skipped every step before it?

of course not

**Comment by bghira** [comment]
well you would have run poetry install before configure which does install torch.
