### ISSUE TITLE
allow random seed for validation image

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#103]
Would be helpful to allow different seed for validation image so the model can be sampled more broadly.

**Comment by bghira** [comment]
well, okay. it's done but i assume english isn't your first language so i will try not to take it personally, just advisement that the tone of the message felt very demanding and i do this work in my spare time, it's hard not to feel unappreciated or whatever when that comes across. :shrug: 

```
  --validation_randomize
                        If supplied, validations will be random, ignoring any seeds.
  --validation_seed VALIDATION_SEED
                        If not supplied, the value for --seed will be used. If neither those nor --validation_randomize are supplied, a seed of zero is used.
```

**Comment by zhuliyi0** [comment]
Sorry if I sounded demanding, definitely not my intention. I will re-phrase it.

**Comment by bghira** [comment]
i figured you hadn't :) i just needed to get that off my chest. we are still friends. :+1:
