### ISSUE TITLE
Training flux lora on small images

### ISSUE THREAD

**Issue by preethamp0197** [bghira/SimpleTuner#1090]
I want to train flux lora on small text crops. And usually the size of these crops are small. So my multidatabackened.json looks like this
[
    {
      "id": "pseudo-camera-10k-flux",
      "type": "local",
      "crop": true,
      "crop_aspect": "square",
      "crop_style": "center",
      "resolution": 512,
      "minimum_image_size": 32,
      "maximum_image_size": 32,
      "target_downsample_size": 512,
      "resolution_type": "pixel_area",
      "cache_dir_vae": "cache/vae/flux/pseudo-camera-10k",
      "instance_data_dir": "datasets/pseudo-camera-10k",
      "disabled": false,
      "skip_file_discovery": "",
      "caption_strategy": "filename",
      "metadata_backend": "discovery",
      "repeats": 0
    }

But I get this error                                                                                                                            
 Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory
  File "SimpleTuner/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 491, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.
    
    
What can I do to solve this issue?

**Comment by bghira** [comment]
use a cuda 12.4 img
