### ISSUE TITLE
Flux AI Toolkit preset generate completly noisy image in Comfy UI.

### ISSUE THREAD

**Issue by axel578** [bghira/SimpleTuner#1119]
It might not necessarely be a Comfy UI issue since all flux lora training I did on kohya/onetrainer seems to work, and the issue seems to be pretty recent seens it was working with simpletuner before, I used two days old simpletuner version, yet the new version did'nt seem to fix it.

I used your default flux lora training especially with quanto (let me know if its the issue) and use flux target ai-toolkit
Just so you can test it a lora: https://drive.google.com/file/d/1mpFHMTOfbAXVLKKj8A5IfWLr0VIoT32K/view?usp=sharing

**Comment by bghira** [comment]
ai-toolkit target is not really supported. it is probably safe to remove now, in fact. i would recommend just `all` or `all+ffs` for LoRA.

but really LoRA is kinda outdated tech by now. LyCORIS LoKr works much better.

**Comment by bghira** [comment]
LoKr has nothing to do with multi-resolution, that's the underlying model at play. unless @KohakuBlueleaf can explain if I am overlooking something.
