### ISSUE TITLE
bugs about mask loss

### ISSUE THREAD

**Issue by LianShuaiLong** [bghira/SimpleTuner#1122]
How should I set the location of the pt files for the mask image? After setting the parameters dataset_type=conditioning, conditioning_type=mask, and conditioning_data according to ### Masked loss, I found a batch of pt files appearing in the Simpletuner folder when running the program. Are these the results of the VAE encoding of the mask images?

**Comment by bghira** [comment]
that does sound like the problem.

you are on the latest release branch?

try setting the VAE cache path for those datasets. it will place them into a folder then.

**Comment by LianShuaiLong** [comment]
all pt files are placed in path:":"/dockerdata/Datasets/MultiMod/MultiMod_combination_v1_Masks_cache/vae/flux" after i configure "cache_dir_vae" like 
`{
    "id":"MultiMod_combination_v1-conditioning",
    "type":"local",
    "dataset_type":"conditioning",
    "instance_data_dir":"/dockerdata/Datasets/MultiMod/MultiMod_combination_v1_Masks",
    "resolution":1024,
    "minimum_image_size":1024,
    "maximum_image_size":1024,
    "target_downsample_size":1024,
    "crop":"False",
    "crop_aspect":"square",
    "crop_style":"center",
    "resolution_type":"pixel",
    "conditioning_type":"mask",
    "cache_dir_vae":"/dockerdata/Datasets/MultiMod/MultiMod_combination_v1_Masks_cache/vae/flux"
  },`
