### ISSUE TITLE
why error in test. how to solve it ?

### ISSUE THREAD

**Issue by taozhiyuai** [bghira/SimpleTuner#1124]
hi. why error in test. how to solve it ?.thanks.

`(simpletuner) taozhiyu@Mac SimpleTuner % poetry run python -m unittest discover tests/
transformer/config.json: 100%|██████████████████| 360/360 [00:00<00:00, 430kB/s]
diffusion_pytorch_model.safetensors: 100%|████| 280k/280k [00:00<00:00, 640kB/s]
text_encoder/config.json: 529B [00:00, 851kB/s]                                 
model.safetensors: 100%|█████████████████████| 283k/283k [00:00<00:00, 2.13MB/s]
unet/config.json: 100%|████████████████████████| 438/438 [00:00<00:00, 1.74MB/s]
An error occurred while trying to fetch hf-internal-testing/tiny-stable-diffusion-pipe: hf-internal-testing/tiny-stable-diffusion-pipe does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
diffusion_pytorch_model.bin: 100%|██████████| 5.82M/5.82M [00:09<00:00, 601kB/s]
text_encoder/config.json: 534B [00:00, 627kB/s]                                                                        
pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 301k/301k [00:01<00:00, 265kB/s]
transformer/config.json: 100%|████████████████████████████████████████████████████████| 359/359 [00:00<00:00, 1.90MB/s]
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████| 1.34M/1.34M [00:00<00:00, 2.92MB/s]
text_encoder_2/config.json: 543B [00:00, 1.66MB/s]                                                                     
model.safetensors: 100%|████████████████████████████████████████████████████████████| 287k/287k [00:00<00:00, 11.0MB/s]
unet/config.json: 1.59kB [00:00, 8.91MB/s]                                                                             
An error occurred while trying to fetch hf-internal-testing/tiny-stable-diffusion-xl-pipe: hf-internal-testing/tiny-stable-diffusion-xl-pipe does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
diffusion_pytorch_model.bin: 100%|████████████████████████████████████████████████| 8.08M/8.08M [00:05<00:00, 1.37MB/s]
text_encoder_2/config.json: 543B [00:00, 1.41MB/s]                                                                     
pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 306k/306k [00:01<00:00, 178kB/s]
text_encoder/config.json: 529B [00:00, 1.30MB/s]                                                                       
pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 302k/302k [00:00<00:00, 449kB/s]
..............................
----------------------------------------------------------------------
Ran 73 tests in 43.566s

OK (skipped=3)`

**Comment by bghira** [comment]
normal outputs

**Comment by taozhiyuai** [comment]
> normal outputs

but the training does not work. how to start it ? my laptop is MAC PRO, m3 max 128GB @bghira
