### ISSUE TITLE
SDXL, EMA, cpu

### ISSUE THREAD

**Issue by pbrownrobo** [bghira/SimpleTuner#1138]
your entry in the README for SDXL, says, 
"4090-24G (no EMA@1024px, batch size 1-4,"

Why no EMA? You dont support EMA on cpu?
OneTrainer does, and there is close to no performance penalty for it.

**Comment by pbrownrobo** [comment]
hm. after a deeper dive into the setup, seems like this bug is really a "your readme.md is out of date, please update".
Since apparently you do support ema on cpu after all.

**Comment by bghira** [comment]
if you are going to compare it to OneTrainer a lot i will simply recommend you stick with that toolkit.

EMA on CPU only doesnt seem to have aperformance impact because it is only updated every 100th step.

post hoc ema is better in every way. old EMA is obsoleted.
