### ISSUE TITLE
bucket bugs

### ISSUE THREAD

**Issue by LianShuaiLong** [bghira/SimpleTuner#1139]
"I have a question to ask. My training dataset contains images of various aspects, with a total data volume of 800. However, during the run, it shows that the data for bucket=1.0 is 800. Here is the configuration of my dataset.json:
`[
  {
    "id": "xxx",
    "type": "local",
    "crop": "False",
    "crop_aspect": "square",
    "crop_style": "center",
    "resolution": 1024,
    "maximum_image_size": 1280,
    "minimum_image_size":0,
    "target_downsample_size": 1024,
    "resolution_type": "pixel",
    "cache_dir_vae": "/dockerdata/Datasets/xxx_cache/vae/flux/",
    "instance_data_dir": "/dockerdata/Datasets/xxx_v2",
    "disabled": false,
    "caption_strategy": "textfile",
    "metadata_backend": "json",
    "prepend_instance_prompt":false,
    "instance_prompt":"xxx style"
  },
  {
    "id": "text-embeds",
    "type": "local",
    "dataset_type": "text_embeds",
    "default": true,
    "cache_dir": "/dockerdata/Datasets/xxx_cache/text/flux/",
    "disabled": false,
    "write_batch_size": 128
  }
]`

**Comment by bghira** [comment]
probably because you have a string value instead of actually false for crop.
