### ISSUE TITLE
Plans to support FLUX inpainting model training?

### ISSUE THREAD

**Issue by huxian0402** [bghira/SimpleTuner#1171]
Excellent open-source code! May I ask if there are any plans to support FLUX inpainting model training? @burgalon @imit8ed @kaibioinfo @barakyo @anhi

**Comment by DonStroganotti** [comment]
As far as I know there is no inpainting model for Flux.

**Comment by bghira** [comment]
please don't ping contributors to ask about a feature request. you could open a pull request to introduce inpainting training support. but if you look carefully, there is zero inpainting training support right now as it is. you are asking for a lot.
