### ISSUE TITLE
feature proposal: continue model pre-train

### ISSUE THREAD

**Issue by Mr-Ye-Cao** [bghira/SimpleTuner#1189]
when caption data is a strong bottleneck, i.e. i have lots of similar-category image data without captioning, it would be nice if we offer continue pre-training for model over images only.

**Comment by bghira** [comment]
what are you expecting to happen?

**Comment by Mr-Ye-Cao** [comment]
hope is that Flux can now see dataset previously not seen during initial training, and can generalize over it: we now only need to provide a small number of captioned supervised image data to train a more robust model.

**Comment by bghira** [comment]
if you don't use captions during training for a large enough run, it will just forget how to use them. it will not generalise that way.
