### ISSUE TITLE
Three bugs in text_embeds.py

### ISSUE THREAD

**Issue by aorunge** [bghira/SimpleTuner#1191]
When I set `--num_validation_images` to `20,`  I find it won't work correctly.
And I find two bugs in `helpers/caching/text_embeds.py`:

1. In the function `encode_sd3_prompt`, the variable `num_images_per_prompt` is fixed to 1,  which should be equal to the `--num_validation_images` when `is_validation` is `true`.
2. In the function `_encode_sd3_prompt_with_clip`,  the `pooled_prompt_embeds` should also be duplicated. Maybe these two lines of code need to be added:

``` python
pooled_prompt_embeds = pooled_prompt_embeds.repeat(1, num_images_per_prompt, 1)
pooled_prompt_embeds = pooled_prompt_embeds.view(batch_size * num_images_per_prompt, -1)
```
I find one bug in `helpers/models/sd3/pipeline.py` too, but it seems that the problem also exists in the implementation of `StableDiffusion3Pipeline` in `diffusers`.

```python
class StableDiffusion3Pipeline:
        ....
       def __call__(...):
            if prompt is not None and isinstance(prompt, str):
                batch_size = 1
            elif prompt is not None and isinstance(prompt, list):
                batch_size = len(prompt)
            else:
                batch_size = prompt_embeds.shape[0]
        ....
            latents = self.prepare_latents(
            batch_size * num_images_per_prompt,
            num_channels_latents,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
            latents,)
```

For example, when I want to generate 20 images for one prompt, the shape of the precomputed prompt_embeds will be [20, 333, 4096]. If we use the ablove codes to calculate the batch_size, when we call the latents = self.pepare_latents(), the value of batch_size * num_images_per_prompt will be 400, which is obviously wrong.

Therefore, the current implementation of StableDiffusion3Pipeline using prompt_embeds precomputed is only correct when generating only one image for one prompt.

**Comment by bghira** [comment]
wrong

**Comment by bghira** [comment]
it just doesn't work, and isn't recommended to use. but setting it so that it will encode 4 prompts inside one will just waste disk space.

**Comment by aorunge** [comment]
> it just doesn't work, and isn't recommended to use. but setting it so that it will encode 4 prompts inside one will just waste disk space.

Thanks for your reply. But if I want to evaulate the CLIP score every 5 steps when training,  it needs more than one images generated for one prompt to calculate the CLIP score. Maybe it's useful when we want to quantify the effect of fine-tuning during training.

**Comment by bghira** [comment]
add multiple resolutions.

**Comment by bghira** [comment]
(CLIP scoring doesn't require >1 image per prompt)

**Comment by aorunge** [comment]
> add multiple resolutions.

Thank you very much!
