### ISSUE TITLE
NameError: name 'AutoencoderKL' is not defined

### ISSUE THREAD

**Issue by mobilejammer** [bghira/SimpleTuner#1245]
name 'AutoencoderKL' is not defined
Traceback (most recent call last):
  File "/home/ubuntu/SimpleTuner/train.py", line 71, in <module>
    trainer.train()
  File "/home/ubuntu/SimpleTuner/helpers/training/trainer.py", line 3232, in train
    AutoencoderKL.from_pretrained(
NameError: name 'AutoencoderKL' is not defined

**Comment by bghira** [comment]
you need to provide your config.

**Comment by mobilejammer** [comment]
> you need to provide your config.

the problem have solved. because you haven't import AutoencoderKL from diffuers

**Comment by bghira** [comment]
the model_family is kind of important to know

**Comment by mobilejammer** [comment]
> the model_family is kind of important to know

thank you! I test sd3

**Comment by bghira** [comment]
please provide configs with future issue reports, it makes life easier for the human on this side of the connection where the problem has to be solved. it's tempting to just close any reported issues when it makes it so i have to piece the murder mystery together.
