### ISSUE TITLE
new lease has high cpu usage and very slow

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#143]
pulled today and noticed this. If something is still WIP then please ignore me. I have been using an older version from couple weeks ago and its been doing fine.

**Comment by zhuliyi0** [comment]
also, vram was not release after I ctrl-c.

**Comment by bghira** [comment]
on the release branch / v0.4.1? there is multiprocessing for luminance calculation, and it now uses NumPy. i guess it could be slower on some systems. I noticed a reduction in time spent.

can you try reverting 76a968e26c09e31c89be775b8f9aba07c17c2f06

**Comment by bghira** [comment]
i merged #144 which disables luminance tracking by default unless you add `--track_luminance`.

this disables the tracking for validation as well as training.

**Comment by zhuliyi0** [comment]
I pulled from release branch. Will try when current training is finished.

> on the release branch / v0.4.1? there is multiprocessing for luminance calculation, and it now uses NumPy. i guess it could be slower on some systems. I noticed a reduction in time spent.
> 
> can you try reverting [76a968e](https://github.com/bghira/SimpleTuner/commit/76a968e26c09e31c89be775b8f9aba07c17c2f06)

**Comment by bghira** [comment]
you have to just hit ^C once and then wait for all of the threads to unwind. as i gather, this is what can cause the memory issue.

**Comment by bghira** [comment]
v0.4.2 has this in there plus `--validation_noise_scheduler` and `--validation_num_inference_steps` so that you do not need to maintain those changes locally. i've added euler/euler-a/ddim/ddpm/unipc as options.

**Comment by zhuliyi0** [comment]
ok I re-pulled and ran 0.4.5, whatever you did fixed it. thanks.
