### ISSUE TITLE
bucket warning spam

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#159]
I was doing a test run with 4 images of 1:1 aspect, batch size 2 gradiant accu 2, and I get this warning every epoch:

[WARNING] All buckets exhausted - since this is happening now, most likely you have chronically-underfilled buckets.

I double checked aspect json file, there is nothing wrong with bucketing.

**Comment by bghira** [comment]
this does mean that the buckets are underfilled. there are remnants being discarded in some way, when that occurs.

**Comment by bghira** [comment]
```py
            all_buckets_exhausted = True  # Initial assumption
            for idx, bucket in enumerate(self.buckets):
                self._clear_batch_accumulator()
                available_images = self._get_unseen_images(bucket)
                while len(available_images) >= self.batch_size:
                    logger.debug(
                        f"Bucket {bucket} has {len(available_images)} available images, and our accumulator has {len(self.batch_accumulator)} images ready for yielding."
                    )
                    all_buckets_exhausted = False  # Found a non-exhausted bucket
```

if not even a single bucket is found with remaining images, it falls through to this code. but that's not the "ideal" way to exhaust all of the buckets:

```py
                bucket_count = len(self.exhausted_buckets) + len(self.buckets)
                # Handle exhausted bucket
                if (
                    len(available_images) < self.batch_size
                    and idx == len(self.buckets) - 1
                    and bucket_count > 1
                ):
                    logger.debug(
                        f"Bucket {bucket} is now exhausted and sleepy, and we have to move it to the sleepy list before changing buckets."
                    )
                    self.move_to_exhausted()
                    self.change_bucket()
                elif len(available_images) < self.batch_size and bucket_count == 1:
                    logger.debug(
                        f"Our only bucket {self.current_bucket} is exhausted, so we reset."
                    )
                    self._reset_buckets()
```

one thing i'm not certain of is whether the idx check is wrong. it might be the incorrect check to make here.

**Comment by bghira** [comment]
not sure why it didn't happen to reset "properly" in the elif condition at the end, where available images are less than our batch size, and we have one bucket remaining. this check occurs after the yield, so the images should be gone already.

**Comment by bghira** [comment]
after the reset_buckets in the elif, it should have been `return` None after. i think maybe it did actually reach that code, but we don't see the debug log, and then it continued down to the failsafe.

please try the main branch, which includes the commit.

**Comment by zhuliyi0** [comment]
it is fixed. thanks!
