### ISSUE TITLE
Exception: No images were discovered by the bucket manager in the dataset.

### ISSUE THREAD

**Issue by sneccc** [bghira/SimpleTuner#191]
what do you recommend doing in this case:
![image](https://github.com/bghira/SimpleTuner/assets/61990796/2470efbf-ea1e-4c8d-b8aa-be99a205faa2)

**Comment by bghira** [comment]
you have 10 buckets that had insufficient samples, and with just 24 samples in the whole set that's quite a few samples that might have been removed.

if your training batch size is, for example, 4, you need at least 4 images in each bucket.

if you're using multiple GPUs, you'll likely need even more images. batch_size quantity per gpu, per bucket, minimum.

the minimum image size is set to avoid upscaling images. if you are fine with whatever scaling occurs, go ahead and set the minimum image size to something low, like 128. it will use all images, and their original_size and target_size will be correctly sent to the model during training. i think the impact of this will be low with SDXL.
