### ISSUE TITLE
ztsnr seems to cause validation image to be de-saturated and generaly looks worse

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#195]
leave all other settings unchanged, rescale_betas_zero_snr causes validation image to look worse. I am training the original SDXL base. Does it only work with v-pred model?

**Comment by bghira** [comment]
yes basically

**Comment by bghira** [comment]
you might need to set the other options for timestep spacing to `trailing`.

otherwise, unfortunately your only option is to push it all the way to v-prediction or to try fine-tuning `ptx0/pseudo-xltest`, which has its own issues. but an updated one will be pushed, this weekend.

**Comment by bghira** [comment]
try using min-snr gamma as well, with a value of 5.
