### ISSUE TITLE
sdxl Refiner

### ISSUE THREAD

**Issue by sneccc** [bghira/SimpleTuner#214]
Hello is there any way to finetune refiner model? lora  or full finetune , when i load in kohya keys are mismatched as expected..

**Comment by bghira** [comment]
unfortunately, that isn't supported yet

**Comment by bghira** [comment]
we don't make use of pytorch-lightning, so such trainer configs are very little value here. instead, it requires careful consideration of how text embeds are generated and how we pass args into the u-net. additionally, it has some conditional inputs that the base SDXL doesn't have (aesthetic scores) and it's not clear how to add those.

i would honestly rather people just bias the timestep range of the base SDXL model on the earliest 200 timesteps and then just pretend it is a refiner. it will have better prompt adherence.

**Comment by zhuliyi0** [comment]
> we don't make use of pytorch-lightning, so such trainer configs are very little value here. instead, it requires careful consideration of how text embeds are generated and how we pass args into the u-net. additionally, it has some conditional inputs that the base SDXL doesn't have (aesthetic scores) and it's not clear how to add those.
> 
> i would honestly rather people just bias the timestep range of the base SDXL model on the earliest 200 timesteps and then just pretend it is a refiner. it will have better prompt adherence.

Speaking of which, have you had any valid result with timestep bias? I played a little bit but havn't had time to really go deep.

Is the HF article about timestep bias out somewhere? Google didn't give me a link.

**Comment by bghira** [comment]
it isn't out yet because the training was restarted and the goal is to hit 55,000 steps. we're on about 32,000 now.

**Comment by bghira** [comment]
here's some data without any context.

![image](https://github.com/bghira/SimpleTuner/assets/59658056/f1fe9736-5ab0-4a3c-9e07-09abc43c33bf)

**Comment by zhuliyi0** [comment]
seems you are training a model that focuses on the first 500 steps but still has decent knownledge of the rest? and it will be used together with a base model that are trained without bias, just like SDXL's base and refiner? If that's the case, the validation images during training will need both models?

**Comment by bghira** [comment]
the goal here is to make a base model that does not **require** a 2nd pass.

**Comment by bghira** [comment]
this is now in the next release
