### ISSUE TITLE
Running Terminus XL Velocity v1 on comfui 

### ISSUE THREAD

**Issue by sneccc** [bghira/SimpleTuner#217]
Hello, recently saw your new models , they need to be snr compatible , but i was wondering if there is a node for comfyui already to make it compatible since they have support to load diffuser models
![image](https://github.com/bghira/SimpleTuner/assets/61990796/138c0bd1-68f9-4385-9297-b5e8b9ffcbd8)

**Comment by bghira** [comment]
i don't use ComfyUI, so i cannot provide guidance on that. it's not an issue with SimpleTuner, really.

**Comment by bghira** [comment]
@Beinsezii can you please provide a workflow / link to the nodes which are required for this? please :-)

**Comment by Beinsezii** [comment]
I have a "make vpred" node in [my node pack](https://github.com/Beinsezii/bsz-cui-extras) that can make the images usable, but without the zsnr beta rescale fix they won't look quite correct.

Additionally the make vpred node is pretty buggy, you have to use it on the first gen after the model loads or it gets confused. Really comfy should implement it properly in a checkpoint loader which he mentioned would be easy to after the latest refactor.

I *might* be able to port the diffusers ddim + beta rescale as a scheduler input for the "custom sampler" node but I'm not quite sure my brain is wrinkly enough for that yet.

**Comment by Beinsezii** [comment]
> yeah iam getting this bug with your node

Close the ComfyUI terminal and reopen it if that happens. Don't close the browser window. I don't know how to fix that. Comfy needs to make a new custom/advanced checkpoint loader node now that his lib supports velocity prediction properly.

 > What is exactly the zsnr beta rescale fix ?

The scheduler needs adjusting to properly accommodate targeting zero terminal SNR. Currently the only library that supports that is diffusers.

**Comment by Beinsezii** [comment]
@sneccc @bghira Comfy just added official support for this and my monkey-patch node is no longer needed. We can close this issue now.
https://github.com/comfyanonymous/ComfyUI/commit/844dbf97a71b398301e1a6318c6776bc5b1f5b7e
