### ISSUE TITLE
bucket_worker fails when metadata_updates_queue is None

### ISSUE THREAD

**Issue by keturn** [bghira/SimpleTuner#225]
```
Process Process-1:                                                                                                                                                          
Traceback (most recent call last):
  File "multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "SimpleTuner/helpers/multiaspect/bucket.py", line 201, in _bucket_worker
    metadata_updates_queue.put(local_metadata_updates)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'put'        
```

probably from https://github.com/bghira/SimpleTuner/blob/18ed7727ae10639c6e38f4b4493499167b235a59/helpers/multiaspect/bucket.py#L644-L652

**Comment by keturn** [comment]
I tried reordering those calling args to what I thought matched the method signature. That got me past that immediate error, but then was very quick to crash with "Some images were not correctly cached during the VAE Cache operations," so I'm not sure that was the right thing to do after all.

**Comment by bghira** [comment]
i need a bit more info about the setup and what is going on when this occurs. the traceback starts in Multiprocessing, which isn't too helpful

**Comment by bghira** [comment]
i believe this is now resolved. but i wasn't able to reproduce the VAE cache issue. that usually occurs when the training script can't identify images, or their resolution is below the configured/default minimum image size.
