### ISSUE TITLE
Saving checkpoint hangs when using DeepSpeed

### ISSUE THREAD

**Issue by zjysteven** [bghira/SimpleTuner#262]
Hi,

First, thank you for all your suggestions earlier, which are helpful.

I found that when using DeepSpeed, `accelerator.save_state()` will hang. According to https://github.com/huggingface/diffusers/issues/2606#issuecomment-1469234268, it can be fixed by calling `accelerator.save_state()` for all processes (rather than only for the main process).

https://github.com/bghira/SimpleTuner/blob/8e9668bd190dd007314662813bc4877f915eae1d/train_sdxl.py#L1323-L1327

Also, I find that the fix mentioned this comment https://github.com/huggingface/diffusers/issues/2606#issuecomment-1704077101 is also necessary for the save hook to work normally in my case.

**Comment by bghira** [comment]
is that JUST for deepspeed? or should we call save_state on all GPUs always?

**Comment by zjysteven** [comment]
I guess it might just be for deepspeed. Unfortunately I cannot test without deepspeed due to limited GPU memory.

**Comment by bghira** [comment]
24G should be enough to train without DeepSpeed, but if you're on 16G all bets are off.

**Comment by zjysteven** [comment]
I am using 24G and I'm training addition parameters for SDXL's unet (for GLIGEN). Somehow I got OOM if not using DeepSpeed.

**Comment by bghira** [comment]
be sure to use adafactor optimizer and pytorch 2.1.3 or so

**Comment by bghira** [comment]
please test the release branch version.

**Comment by zjysteven** [comment]
I will test when I get a chance. Closing the issue for now. Thanks!
