### ISSUE TITLE
how to enable multi-GPU training

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#303]
Should I set --num_processes=2 and/or --num_machines=2 ? I tried both but don't seem to work. The same dataset and setting works fine with single GPU on the same machine, until it OOMs out.

When I set process=2, I can see 2 GPU loading the same amount of data into vram until OOM, same as running with single GPU.

**Comment by bghira** [comment]
the settings are per-GPU. multi-GPU training is enabled automatically if num_processes > 1.

it is DataParallel training, not ModelParallel training. the layers / components of the model are not spread across GPUs in the way you are imagining, it loads a separate copy of the model onto each GPU and runs a shard of the data on each. their gradients are accumulated and then combined in the backward pass. you can think of it roughly as equal to `--gradient_accumulation_steps`.

**Comment by zhuliyi0** [comment]
I see. That makes sense otherwise A100 would be useless since 4x4090 is even better.

**Comment by zhuliyi0** [comment]
effective batch size = gpu x batch x grad accu, correct?

**Comment by bghira** [comment]
yes
