### ISSUE TITLE
Image size check after resizing?

### ISSUE THREAD

**Issue by naoto0804** [bghira/SimpleTuner#319]
First of all, thank you for making a great project publicly available!

Why is [this part](https://github.com/bghira/SimpleTuner/blob/e5d9bf71ff29e2e4ec570dd79f0e2207c83e2560/helpers/multiaspect/image.py#L47-L52) 
```python
image, crop_coordinates = MultiaspectImage.prepare_image(
    image,
    bucket_manager.resolution,
    bucket_manager.resolution_type,
    data_backend.id,
)
```
executed before [this part](https://github.com/bghira/SimpleTuner/blob/e5d9bf71ff29e2e4ec570dd79f0e2207c83e2560/helpers/multiaspect/image.py#L64-L66)?
```python
if not bucket_manager.meets_resolution_requirements(
    image=image,
):
    logger.debug(
        f"Image {image_path_str} does not meet minimum image size requirements. Skipping image."
    )
    statistics["skipped"]["too_small"] += 1
    return aspect_ratio_bucket_indices
```

I first thought `minimum_image_size` is used to filter out low-resolution images, but those images are upsampled by `prepare_image`, as far as I watch the debug logs.

![resize_before_size_check](https://github.com/bghira/SimpleTuner/assets/7067992/d957bd4f-2230-4eae-93eb-b2d5b7cb0a91)

**Comment by bghira** [comment]
it will be nice if this can be optimised, but that's also a really difficult section of code that has been carefully altered over time to give the best chances at success.

i will investigate when i have time

**Comment by bghira** [comment]
oh, those images should definitely be excluded still. i thought the problem was that it just computes their new size unnecessarily?

**Comment by bghira** [comment]
can you re-check this on the latest master branch? please and thank you for the report
