### ISSUE TITLE
controlnet support?

### ISSUE THREAD

**Issue by universewill** [bghira/SimpleTuner#338]
Will this tuner support controlnet training ?

**Comment by bghira** [comment]
not really sure what that entails, but i'd gladly review a pull request

**Comment by bghira** [comment]
with v0.9.5 there's new infrastructure to support eventually adding controlnet training.

eg. `helpers/training/sample.py` contains a lot of important encapsulation logic for training samples.

a data backend could have a retrieval helper that the training sample hooks into to eg. obtain its conditioning input image from the appropriate location.

**Comment by bghira** [comment]
see the `feature/controlnet` branch for an early version

there's an example dataloader configuration in the pull request: #407 

there's a script in `toolkit/datasets/controlnet` that will generate a canny edge map set for your images.

it seems to mostly work, though it's SDXL only, and there's no real documentation for it yet.

**Comment by bghira** [comment]
see [this document](https://github.com/bghira/SimpleTuner/blob/main/documentation/CONTROLNET.md)
