### ISSUE TITLE
How much VRAM to finetune SDXL?

### ISSUE THREAD

**Issue by xiankgx** [bghira/SimpleTuner#35]
Hi, I got to know of this repository from the diffusers Github issues.

From your experience, how much VRAM is required to finetune SDXL 1.0? I only have access to small GPUs like AWS G5.

**Comment by bghira** [comment]
when you say small GPUs, you mean multiple of them? the G5 comes with up to 10, NVIDIA A10G.

this repo has preliminary multi-gpu support, but there are some problems. i don't have funding to access a multi-gpu system for long enough to resolve this.

**Comment by xiankgx** [comment]
Maybe just 1 to 8 at most. The thing is is 23GB VRAM per GPU enough for training? What is your experience with LoRA?

**Comment by bghira** [comment]
currently the theory is using Adafactor will make it work at batch size 1 for 24G but it's not really worth it to me.

no experience with LoRA

**Comment by bghira** [comment]
I would say 48G minimum.
