### ISSUE TITLE
Use of variant

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#351]
Hi there! First of all, thank you for developing this library. I've been trying to fine-tune on top of [Juggernaut](https://huggingface.co/RunDiffusion/Juggernaut-XL-v9) which only has the `fp16` variant of the model in their repository.

Running the `train_sdxl.py` script, I'm getting:
```
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 300, in main
    text_encoder_1 = text_encoder_cls_1.from_pretrained(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3240, in from_pretrained
    raise EnvironmentError(
OSError: orionsoftware/juggernaut-XL-v9 does not appear to have a file named pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True` to load this model from those weights.
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

A temporary workaround has been to fork the repository and rename the files, but it would be nice to have a `--variant` CLI arg [like the original HF script](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L155).

If you're accepting PR's I can give it a try.

**Comment by bghira** [comment]
i actually am not a fan of how Huggingface implemented variants, and it seems like they're not a fan of it, either.

the Stable Cascade stuff seems confused with how to proceed with variants.

there's several places to ensure the variants are used correctly, if you do decide to move forward with a PR.

**Comment by BuildBackBuehler** [comment]
I've had no problems relating to FP16 variants and that's what I use. Albeit, I had to convert my CivitAI singular model file into the divvied up vae/unet etc. checkpoint and it sounds like you are trying to directly integrate the HF Juggernaut model? 

There **is** the revision CLI arg. and I'm pretty sure it acts as variant. Least I've been using --revision fp16 and based on the train_sdxl.py code, its using that revision info where I imagine variant FP16 would be relayed.

(or variant= fp16 just never mattered for me because it was a converted file to begin with, like your workaround)

**Comment by bghira** [comment]
you might be right, i recall looking into the code for `revision` to see what it did inside huggingface_hub and i believe it checks for a .<revision>.safetensors variant as well as an entire git branch with that name.
