### ISSUE TITLE
piecewise rectified flow

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#364]
it sure would be nice to have [this](https://github.com/magic-research/piecewise-rectified-flow/blob/main/scripts/train_perflow.py) technique integrated into simpletuner.

essentially, PeRF extends the concept of rectified flow to have multiple segments and continuous noise schedule, which allows the use of more steps at inference time to improve the image quality, whilst still allowing the use of the model at or below ~4 steps.

the example training code is very easy to understand, it will just take some time.

**Comment by BuildBackBuehler** [comment]
This sounds great to me! 

At least as far as I understand -- it doesn't require its own ecosystem like LCMs/Turbo models do. AKA you you can swap in/out any old model/LoRA to go with your PeRFlow model/LoRA. 

I was looking @ the code and yeah it seems like it can easily be integrated, or as it seemed with the Kohya Keys showing. It looks pretty modular. I'll try and see what I can do, but I imagine someone will beat me to the punch.

**Comment by bghira** [comment]
nope, it needs its own pipelines and schedulers

**Comment by bghira** [comment]
after consideration, piecewise rectified flow is probably not creative enough and not worth including due to its complexity / requirement for teacher/student models to be loaded.
