### ISSUE TITLE
when setting max train steps less than a full epoch, training exits early

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#365]
when running a training session with:

```
MAX_NUM_STEPS=50000
NUM_EPOCHS=0
```

the training will exit, as it thinks for some reason epoch 1 has already been reached.

other trainers start epochs counting at 0 for this reason, maybe it should here too

**Comment by BuildBackBuehler** [comment]
Adding to this one, I found when I included epochs + steps that whatever max_num_steps I input, that then the num_epochs would be entirely ignored. So I'd put in 1200 m_n_s and 5 n_e and end up with 1200 n_e -- at least as it was shown in my CLI. Can't say I was ready to see if it would stop @ 5 epochs. 

I also presumed that m_n_e was the # intended for 1 entire run. As to say the script wouldn't attempt to reach 1200 steps within 1 epoch but in 5 epochs. Instead I'd expect 1200/5 = 240 steps. So in the CLI epoch 1/5 [progress bar] X/240 steps. No?

**Comment by bghira** [comment]
max num steps is just meant to cap training.

it will use that value to calculate how many epochs to run for:

```py
    # Afterwards we recalculate our number of training epochs
    args.num_train_epochs = math.ceil(args.max_train_steps / num_update_steps_per_epoch)
    logger.info(
        "After removing any undesired samples and updating cache entries, we have settled on"
        f" {args.num_train_epochs} epochs and {num_update_steps_per_epoch} steps per epoch."
    )
```

**Comment by bghira** [comment]
now fixed in the master branch, num epochs / max train steps must be defined independently, they cannot be both defined.
