### ISSUE TITLE
 [ERROR] (TextEmbeddingCache) Failed retrieving prompt from cache

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#389]
Error at the first validation:

Epoch 1/122, Steps:   0%|▏                                 | 200/40000 [12:23<38:22:47,  3.47s/it, lr=1e-5, step_loss=0.0971]2024-05-11 10:45:14,534 [INFO] (validation) Running validation... 
 Generating 6 images.
[2024-05-11 10:45:24,936] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
df: /root/.triton/autotune: No such file or directory
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
                                                                                                                                                                 Loaded scheduler as EulerDiscreteScheduler from `scheduler` subfolder of /root/autodl-tmp/sd_xl_base_1.0.                                    | 0/3 [00:00<?, ?it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 866.17it/s]
                                                2024-05-11 10:45:26,022 [ERROR] (TextEmbeddingCache) Failed retrieving prompt from cache:
-> prompt: validation images: 0it [00:00, ?it/s]
-> filename: /root/textembed_cache/siteplan600/d41d8cd98f00b204e9800998ecf8427e-sdxl.pt
-> error: /root/textembed_cache/siteplan600/d41d8cd98f00b204e9800998ecf8427e-sdxl.pt not found.
-> id: embed-cache-siteplan600, data_backend id: embed-cache-siteplan600
                                                Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/sdxl_embeds.py", line 418, in compute_embeddings_for_sdxl_prompts
    prompt_embeds, add_text_embeds = self.load_from_cache(filename)
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/sdxl_embeds.py", line 150, in load_from_cache
    result = self.data_backend.torch_load(filename)
  File "/root/autodl-tmp/SimpleTuner/helpers/data_backend/local.py", line 171, in torch_load
    raise FileNotFoundError(f"{filename} not found.")
FileNotFoundError: /root/textembed_cache/siteplan600/d41d8cd98f00b204e9800998ecf8427e-sdxl.pt not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train_sdxl.py", line 1442, in main
    log_validations(
  File "/root/autodl-tmp/SimpleTuner/helpers/legacy/validation.py", line 391, in log_validations
    ) = embed_cache.compute_embeddings_for_prompts([validation_prompt])
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/sdxl_embeds.py", line 354, in compute_embeddings_for_prompts
    output = self.compute_embeddings_for_sdxl_prompts(
  File "/root/autodl-tmp/SimpleTuner/helpers/caching/sdxl_embeds.py", line 429, in compute_embeddings_for_sdxl_prompts
    raise Exception("This won't work. We cannot continue.")
Exception: This won't work. We cannot continue.

**Comment by zhuliyi0** [comment]
I use json for validation prompt.

**Comment by bghira** [comment]
there's not enough info to go on but as you use a non-standard method to launch the trainer i'm curious if using the shell script to start it would change things.

**Comment by bghira** [comment]
@zhuliyi0 were you able to make it work? i'm able to train SD 1.5, SD 2.x, SDXL and DeepFloyd without issues.

**Comment by zhuliyi0** [comment]
I tried running with the default .sh, with minimal change to env file (only dir and batch size etc), got this error at first validation:

O] (validation) Running validation... 
 Generating 2 images.
[2024-05-13 09:09:51,138] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
                                                                                                                                                        Loaded scheduler as EulerDiscreteScheduler from `scheduler` subfolder of /root/autodl-tmp/sd_xl_base_1.0.                           | 0/3 [00:00<?, ?it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1016.88it/s]
                                                Traceback (most recent call last):
  File "/root/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/root/SimpleTuner/train_sdxl.py", line 1442, in main
    log_validations(
  File "/root/SimpleTuner/helpers/legacy/validation.py", line 516, in log_validations
    pipeline(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/SimpleTuner/helpers/sdxl/pipeline.py", line 1348, in __call__
    if self.do_classifier_free_guidance and self.guidance_rescale > 0.0:
[sdxl-env.txt](https://github.com/bghira/SimpleTuner/files/15288316/sdxl-env.txt)

TypeError: '>' not supported between instances of 'tuple' and 'float'


I also noticed the training speed is faster than from running directly from command. Bitfit is turned on by default for finetuning, is that the cause of speed up?

my config attached.

**Comment by zhuliyi0** [comment]
about the speed, I was using a small test set of 2 images. When I switch back to the real dataset with 60 images, the speed seems to be the same as before, so probably something with dataset size?

**Comment by zhuliyi0** [comment]
I am trying a brand new install on Runpod. I suspect it is some dependency version conflict. I wasn't able to use poetry due to network issue, had to convert poetry to pip.

**Comment by zhuliyi0** [comment]
Strange, I keep getting http error when downloading sdxl from huggingface on Runpod. Will need to follow up another day. 

I wasn't able to install with poetry on Runpod either, not sure what's the cause, maybe root user restriction? Dependencies not showing up after poetry claiming installed all. Had to use pip again. I can only see two version restrictions in .toml file so I assume it should be OK to use pip?

**Comment by bghira** [comment]
well i ran into this on a local setup with very few images in it. i had to add a bit of a sleep to the end so that the thread can unwind before the trainer continues. can you verify that?
