### ISSUE TITLE
Use model VAE

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#394]
I see that the default VAE for training is `madebyollin/sdxl-vae-fp16-fix`, but I'm doing bf16 where that fix is not useful. I've tried setting `--pretrained_vae_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0` & `--pretrained_vae_model_name_or_path=""` neither of which worked.

How can I get the script to use the VAE of the model I have specified via `--pretrained_model_name_or_path`?

**Comment by bghira** [comment]
you can't use bf16 with the original VAE, either.

in fact, the original VAE has `force_upcast=True`

please don't use the original SAI VAE. it is flawed.

**Comment by komninoschatzipapas** [comment]
Gotcha
