### ISSUE TITLE
Perform validation on step 0

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#405]
Would be neat so we can tell how much we managed to improve from the base model when using a small training set.

I managed to hack it on my local copy by adding `validation.run_validations(validation_type="intermediary", step=global_step, force_evaluation=True)` right after `validation` is declared on the train scripts.

**Comment by bghira** [comment]
while that'd work i think i'd like to do a bit more like write them to a specific path for the base model's validations, then we'd be able to easily retrieve them upon intermediary validations and do an optional side-by-side comparison for each ckpt.
