### ISSUE TITLE
WARNING - root - Cannot continue. There are not enough images to form a single batch

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#44]
I receive a barrage of warnings with bucket info and have no idea what is happening.  Most images in my dataset are over 1024x1024. Do I have to square them all to 1024x1024?  I didn't notice any information about data preparation in the docs. 
  

```
08/18/2023 16:29:07 - WARNING - root - Not enough unseen images (0) in the bucket: 0.802
08/18/2023 16:29:07 - INFO - root - Bucket 0.802 is empty or doesn't have enough samples for a full batch. Moving to the next bucket.
08/18/2023 16:29:07 - DEBUG - root - Active Buckets: 0.8 (remaining: 2), 1.0 (remaining: 2), 0.883 (remaining: 1), 0.801 (remaining: 1), 0.955 (remaining: 0)
08/18/2023 16:29:07 - DEBUG - root - Exhausted Buckets: 1.021 (remaining: 0), 0.802 (remaining: 1)
08/18/2023 16:29:07 - INFO - root - Changing bucket to 0.8.
Steps:  76%|_____________________________________________________________________________________________________________________                                    | 114/150 [12:11<03:40,  6.13s/it, lr=1e-6, step_loss=0.143]
08/18/2023 16:29:12 - WARNING - root - Not enough unseen images (0) in the bucket: 0.801
08/18/2023 16:29:12 - INFO - root - Bucket 0.801 is empty or doesn't have enough samples for a full batch. Moving to the next bucket.
08/18/2023 16:29:12 - DEBUG - root - Active Buckets: 0.8 (remaining: 2), 1.0 (remaining: 2), 0.883 (remaining: 1), 0.955 (remaining: 0)
08/18/2023 16:29:12 - DEBUG - root - Exhausted Buckets: 1.021 (remaining: 0), 0.802 (remaining: 1), 0.801 (remaining: 1)
08/18/2023 16:29:12 - INFO - root - Changing bucket to 0.883.
Steps:  76%|____________________________________________________________________________________________________________________                                    | 114/150 [12:12<03:40,  6.13s/it, lr=1e-6, step_loss=0.0956]
08/18/2023 16:29:13 - WARNING - root - Not enough unseen images (0) in the bucket: 0.883
08/18/2023 16:29:13 - INFO - root - Bucket 0.883 is empty or doesn't have enough samples for a full batch. Moving to the next bucket.
08/18/2023 16:29:13 - DEBUG - root - Active Buckets: 0.8 (remaining: 2), 1.0 (remaining: 2), 0.955 (remaining: 0)
08/18/2023 16:29:13 - DEBUG - root - Exhausted Buckets: 1.021 (remaining: 0), 0.802 (remaining: 1), 0.801 (remaining: 1), 0.883 (remaining: 1)
08/18/2023 16:29:13 - INFO - root - Changing bucket to 1.0.
08/18/2023 16:29:13 - WARNING - root - Not enough unseen images (0) in the bucket: 1.0
08/18/2023 16:29:13 - INFO - root - Bucket 1.0 is empty or doesn't have enough samples for a full batch. Moving to the next bucket.
08/18/2023 16:29:13 - DEBUG - root - Active Buckets: 0.8 (remaining: 2), 0.955 (remaining: 0)
08/18/2023 16:29:13 - DEBUG - root - Exhausted Buckets: 1.021 (remaining: 0), 0.802 (remaining: 1), 0.801 (remaining: 1), 0.883 (remaining: 1), 1.0 (remaining: 2)
08/18/2023 16:29:13 - WARNING - root - Only one bucket left, and it doesn't have enough samples. Resetting...
08/18/2023 16:29:13 - WARNING - root - Exhausted buckets: 1.021 (remaining: 0), 0.802 (remaining: 1), 0.801 (remaining: 1), 0.883 (remaining: 1), 1.0 (remaining: 2)
08/18/2023 16:29:13 - INFO - root - After resetting, changed bucket to 0.955.
08/18/2023 16:29:13 - INFO - root - Bucket 0.955 is empty or doesn't have enough samples for a full batch. Moving to the next bucket.
08/18/2023 16:29:13 - DEBUG - root - Active Buckets: 0.8 (remaining: 2)
08/18/2023 16:29:13 - DEBUG - root - Exhausted Buckets: 0.955 (remaining: 0)
08/18/2023 16:29:13 - DEBUG - root - Changing bucket to the only one present.
Steps:  77%|_______________________________________________________________________________________________________________________                                    | 115/150 [12:16<03:34,  6.14s/it, lr=1e-6, step_loss=0.3]
08/18/2023 16:29:16 - DEBUG - root - Active Buckets: 0.8 (remaining: 2)
08/18/2023 16:29:16 - DEBUG - root - Exhausted Buckets: 0.955 (remaining: 0)
08/18/2023 16:29:16 - WARNING - root - Cannot continue. There are not enough images to form a single batch:
    -> Seen images: 2
    -> Unseen images: 0
    -> Buckets: ['0.8']
    -> Batch size: 1
    -> Image list: []

```

**Comment by bghira** [comment]
how many images do you have in your dataset?

**Comment by bghira** [comment]
if you removed `--use_original_images` from your env file. it could cause unintended effects.

i haven't looked at that parameter's implementation in a bit, because we **currently** never crop images for SDXL training.

there's no needed dataset prep, but each aspect bucket does need a minimum number of images in it.

there's another bug reported on Discord where someone observed that the aspect bucketing seemed to ignore a majority of their images.

**Comment by bghira** [comment]
the warning is there as a bit of detective work so that i can determine where the issues arise.

i have completely rewritten the bucket logic code in v0.2.0 (the current git main) - if you try an earlier version, there may be other bugs. but the bucketing logic is different there.

it's possible i've overlooked something in the current code. but i also intentionally ported any issues from the old sampler, so that the behaviour is identical. the code is, however, easier to read and work with. ergo, when i can determine the issue, it is actually solveable now.

if you can direct all of your output into a log file and provide this, i would be greatly appreciative.

**Comment by bghira** [comment]
https://github.com/bghira/SimpleTuner/releases/tag/v0.1.11

tag v0.1.11 or earlier would work. the further back you go, the more some behaviours become hardcoded toward terminal SNR and v_prediction adaptation.

**Comment by bghira** [comment]
> What would be the status of the last saved checkpoint? Not trained at all ? if it didn't train nothing or little, why it never stop even though it says "cannot continue"?

likely unevenly sampled images. oversampling some. never seeing others. over-trained and under-trained at the same time. quite a feat

**Comment by bghira** [comment]
i'm really not sure why it shows so little images for each bucket. something that stands out is the Tiff image plugin being used. all of my images are PNG or JPEG that i've been using.

the other is that it looks like it processes 50 images throughout and finds '100 examples' and then runs through each bucket, which look to contain only one image.

**Comment by bghira** [comment]
please open a new issue if the same occurs on v0.2.2
