### ISSUE TITLE
SD3 training - not unloading text encoders

### ISSUE THREAD

**Issue by OhioT** [bghira/SimpleTuner#457]
When training SD3, despite the line "del text_encoder_1, text_encoder_2, text_encoder_3" definitely executing, memory use with gradient checkpointing remains at ~18GB during training for batch 1 LORA on default settings. (Says 0GB saved, no memory reduced by deleting the text encoders)

Manually editing out the lines where the text encoder is loaded gives ~8GB instead, which is what I would expect with just transformer + VAE loaded. (It loads from the text cache; training runs the same either way)

**Comment by bghira** [comment]
this may be resolved. can you test again?

**Comment by OhioT** [comment]
@bghira Not resolved, because TextEmbeddingCache retains a reference to text_encoders so it isn't deleted.

Deleting before configure_multi_databackend() does free the memory but obviously causes the cache to not work.

**Comment by bghira** [comment]
thanks, i will check

**Comment by bghira** [comment]
thanks for the code snippet. i didn't see much of a difference in memory use on MacOS here, but i haven't yet tested on CUDA.
