### ISSUE TITLE
Possible bug in arguments.py

### ISSUE THREAD

**Issue by janekm** [bghira/SimpleTuner#462]
On line 1474:
`    if not args.adam_bfloat16 and not args.i_know_what_i_am_doing:
        raise ValueError(
            "Currently, only the AdamW optimizer supports bfloat16 training. Please set --adam_bfloat16 to true."
        )
`
Unless I'm missing something, this prevents running with any optimisers than AdamWbf16, and also by turn without BF16 support (It seems I can't use BF16 on the M3 even though I thought theoretically it's supported by the GPU).

**Comment by bghira** [comment]
M3 is absolutely supported, as it's the machine I do development work from.

- ensure MIXED_PRECISION='no'
- ensure you've installed the dependencies as indicated by the INSTALL.md document, eg. passing the `-C install/apple` arg to `poetry`

Stochastic bf16 is actually the only style of training that simpletuner supports. we used to have 8bit adamw but the bitsandbytes library is nvidia-specific and requires autocast to be used, which is AMD and NVIDIA-specific.

autocast produces imprecise results, and is difficult to implement, so, we don't use it at all here.

**Comment by janekm** [comment]
Ah, thanks a lot for the explanation! 
It didn't click for me before that it should be `export OPTIMIZER="adamw_bf16"` (and `export MIXED_PRECISION="no"`) so I was spending ages trying different invalid combinations.

**Comment by bghira** [comment]
thanks for the helpful feedback. that is now force-overridden in the main branch, for the next release.
