### ISSUE TITLE
[Feature Request] Upload validation images to wandb

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [bghira/SimpleTuner#465]
It seems now that validation images are not uploaded to wandb.
It would be very useful to upload the images to wandb.

**Comment by bghira** [comment]
they are ([example](https://wandb.ai/bghira/sd3-training/runs/14853dc305d677f70c0562895dd40a26?nw=nwuserbghira)) do you have any errors on your end?

**Comment by a-l-e-x-d-s-9** [comment]
I can see them now.
Maybe they were minimized before.
Thank you!
