### ISSUE TITLE
Install dependency triton-library: wanted 1.0.0rc3, have only <= 1.0.0rc2

### ISSUE THREAD

**Issue by apurtell** [bghira/SimpleTuner#470]
poetry could install all dependencies except triton-library. 
Manually installing triton-library with pip pulls down and installs 1.0.0rc2. 
Kicked off poetry again and it fails this way:

    Package operations: 0 installs, 1 update, 0 removals
      - Updating triton-library (1.0.0rc2 -> 1.0.0rc3): Failed
      RuntimeError
      Unable to find installation candidates for triton-library (1.0.0rc3)
    Cannot install triton-library.

Environment: Amazon Linux 2 x86_64 
Python 3.11.9
conda 24.5.0
NVIDIA driver version: 535.183.01
CUDA versions available: cuda-12.1
Default CUDA version is 12.1

**Comment by bghira** [comment]
do you know of a solution?

**Comment by nguyendothanhtruc** [comment]
@bghira Hi, I also encounter the similar errors when installing triton-library:
The required version 1.0.0rc3 is not found (only available versions: 1.0.0rc1, 1.0.0rc2).
Python 3.10.13
NVIDIA driver version: 550.54.15
CUDA driver verson: 12.4

**Comment by nguyendothanhtruc** [comment]
@bghira Are there any constraints about CUDA driver or python version to run the project cause we both use CUDA 12.x ?

**Comment by bghira** [comment]
possibly, i use 12.1

**Comment by al-swaiti** [comment]
i was face same issue with python 3.12 ,,, whatever its fixed when i resetup with python 3.10 
![image](https://github.com/user-attachments/assets/7f3c0f4e-e436-43ac-8ff5-f3a4e726cd80)

**Comment by tazztone** [comment]
hi. seems i have the same issue.
while running `C:\_simpletuner\SimpleTuner>pip install -U poetry pip` 
it worked but further down i got this error: ```ERROR: To modify pip, please run the following command: C:\_simpletuner\SimpleTuner\.venv\Scripts\python.exe -m pip install -U poetry pip``` 
so i ran the suggested command:
![image](https://github.com/user-attachments/assets/ecfd2b17-b9f5-43de-bc15-91eda2468996)

but eventually i got the `RuntimeError   Unable to find installation candidates for triton (3.0.0)`:
![image](https://github.com/user-attachments/assets/9fc85704-0f35-4792-a578-965ad95f0db5)
dk how i would be able to continue my installation attempt from here.

**Comment by bghira** [comment]
triton doesn't work on windows

**Comment by tazztone** [comment]
> triton doesn't work on windows

whoah i had no idea simpletuner was for linux and macs only. well sorry for disturbing then ;D
