### ISSUE TITLE
parquet metadata backend has trouble with maintaining aspect ratio when using square crops

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#480]
workaround: disable cropping, recreate aspect  (the json files in your dataset) and vae cache (the .pt files).

it's low priority but if you're relying on this for pretraining large models and you need the error resolved more quickly please ping me on this issue

**Comment by sayakpaul** [comment]
Seems like it's not an issue any longer?

**Comment by bghira** [comment]
correct :) just a couple places it needed to be nudged one way and then the other.
