### ISSUE TITLE
(question)SD3 Training Memory Usage Issue

### ISSUE THREAD

**Issue by pzzmyc** [bghira/SimpleTuner#481]
Regarding the memory usage issue during SD3 training, it starts at 9GB and goes up to 24GB. I tried adding code to clear the cache, which alleviated the issue, but I'm not sure if it's correct. Here is the code I added to clear the cache every 100 steps: 
                ...
                current_epoch_step += 1
                StateTracker.set_global_step(global_step)
                **if global_step % 100 == 0:
                    torch.cuda.empty_cache()
                    gc.collect()
                    print("clear cache")**

                ema_decay_value = "None (EMA not in use)"
                if args.use_ema:
                ....

**Comment by bghira** [comment]
does it OOM? if not, and it's in the cache, it's evictable, which means it's free-able upon need

sometimes the kernel might block a little longer than usual which a low-latency application might decide isn't good enough and give an OOM error instead of waiting.

**Comment by pzzmyc** [comment]
Yes, I am using 24GB graphics cards. Sometimes I encounter a CUDA out of memory error, and sometimes an NCCL error, which is likely also caused by insufficient GPU memory

**Comment by bghira** [comment]
would you like to open a PR for this to optionally run based on an interval?

**Comment by pzzmyc** [comment]
> would you like to open a PR for this to optionally run based on an interval?

I would like to, but I'm not very familiar with these operations on GitHub. How do I do it?

**Comment by bghira** [comment]
- fork the project to your github account
- pull a local copy of it to make changes from
- create a new branch, and commit your changes
- push them to your repository
- open the pull request to this repository

**Comment by bghira** [comment]
please set `--accelerator_cache_clear_interval=500` in your TRAINER_EXTRA_ARGS to enable the new option from @TwoAbove
