### ISSUE TITLE
Validation.__init__() missing 1 required positional argument: 'transformer'

### ISSUE THREAD

**Issue by rengotj** [bghira/SimpleTuner#483]
Good morning,

Epic fail occurs while running train_sd2x.sh : 
![error validation transformer](https://github.com/bghira/SimpleTuner/assets/22301704/b52d3975-6d87-46b3-a31d-313aebca3da7)

Could you explain me how to fix it ? Thankyou.

Best regards.

**Comment by bghira** [comment]
this should be resolved in the lastest main branch

**Comment by rengotj** [comment]
Thank you so much ! Have a good day.
