### ISSUE TITLE
 'NoneType' object has no attribute 'gradient_checkpointing_enable'

### ISSUE THREAD

**Issue by pzzmyc** [bghira/SimpleTuner#485]
I used the --train_text_encoder parameter while training SDXL lora, got an error AttributeError: 'NoneType' object has no attribute 'gradient_checkpointing_enable'.full args is here: 
args:snr_gamma:5.0
args:use_soft_min_snr:False
args:soft_min_snr_sigma_data:None
args:model_type:lora
args:pixart_sigma:False
args:sd3:False
args:sd3_uses_diffusion:False
args:weighting_scheme:logit_normal
args:logit_mean:0.0
args:logit_std:1.0
args:mode_scale:1.29
args:lora_type:None
args:lora_init_type:default
args:lora_rank:16
args:lora_alpha:16
args:lora_dropout:0.1
args:controlnet:False
args:controlnet_model_name_or_path:None
args:pretrained_model_name_or_path:/media/hhy/A983D940A4049592/base/stable-diffusion-xl-base-1.0
args:pretrained_vae_model_name_or_path:madebyollin/sdxl-vae-fp16-fix
args:pretrained_t5_model_name_or_path:None
args:prediction_type:epsilon
args:snr_weight:1.0
args:training_scheduler_timestep_spacing:trailing
args:inference_scheduler_timestep_spacing:trailing
args:refiner_training:False
args:refiner_training_invert_schedule:False
args:refiner_training_strength:0.2
args:timestep_bias_strategy:none
args:timestep_bias_multiplier:1.0
args:timestep_bias_begin:0
args:timestep_bias_end:1000
args:timestep_bias_portion:0.25
args:disable_segmented_timestep_sampling:False
args:rescale_betas_zero_snr:False
args:vae_dtype:bf16
args:vae_batch_size:4
args:vae_cache_scan_behaviour:recreate
args:vae_cache_preprocess:False
args:aspect_bucket_disable_rebuild:False
args:keep_vae_loaded:False
args:skip_file_discovery:
args:revision:None
args:variant:None
args:preserve_data_backend_cache:False
args:use_dora:False
args:override_dataset_config:False
args:cache_dir_text:cache
args:cache_dir_vae:
args:data_backend_config:/media/hhy/A983D940A4049592/base/dataset.json
args:write_batch_size:64
args:enable_multiprocessing:False
args:aspect_bucket_worker_count:12
args:cache_dir:/media/hhy/A983D940A4049592/base/savedmodels/cache
args:cache_clear_validation_prompts:False
args:caption_strategy:filename
args:parquet_caption_column:None
args:parquet_filename_column:None
args:instance_prompt:None
args:output_dir:/media/hhy/A983D940A4049592/base/savedmodels
args:seed:42
args:seed_for_each_device:True
args:resolution:1024.0
args:resolution_type:pixel
args:aspect_bucket_rounding:None
args:aspect_bucket_alignment:64
args:minimum_image_size:1024.0
args:maximum_image_size:None
args:target_downsample_size:None
args:train_text_encoder:True
args:tokenizer_max_length:None
args:train_batch_size:1
args:num_train_epochs:10
args:max_train_steps:None
args:checkpointing_steps:1000
args:checkpoints_total_limit:2
args:resume_from_checkpoint:latest
args:gradient_accumulation_steps:4
args:gradient_checkpointing:True
args:learning_rate:1e-06
args:text_encoder_lr:1e-06
args:lr_scale:False
args:lr_scheduler:constant
args:lr_warmup_steps:1000
args:lr_num_cycles:1
args:lr_power:0.8
args:use_ema:False
args:ema_decay:0.995
args:non_ema_revision:None
args:offload_param_path:None
args:use_8bit_adam:False
args:use_adafactor_optimizer:False
args:adafactor_relative_step:False
args:use_prodigy_optimizer:False
args:prodigy_beta3:None
args:prodigy_decouple:True
args:prodigy_use_bias_correction:True
args:prodigy_safeguard_warmup:True
args:prodigy_learning_rate:0.5
args:prodigy_weight_decay:0.01
args:prodigy_epsilon:1e-08
args:use_dadapt_optimizer:False
args:dadaptation_learning_rate:1.0
args:adam_beta1:0.9
args:adam_beta2:0.999
args:adam_weight_decay:0.01
args:adam_epsilon:1e-08
args:adam_bfloat16:True
args:max_grad_norm:2.0
args:push_to_hub:False
args:push_checkpoints_to_hub:False
args:hub_model_id:None
args:logging_dir:logs
args:validation_torch_compile:False
args:validation_torch_compile_mode:max-autotune
args:allow_tf32:True
args:validation_using_datasets:None
args:webhook_config:None
args:report_to:wandb
args:tracker_run_name:simpletuner-sdxl
args:tracker_project_name:sdxl-training
args:validation_prompt:ethnographic photography of teddy bear at a picnic
args:validation_prompt_library:False
args:user_prompt_library:None
args:validation_negative_prompt:blurry, cropped, ugly
args:num_validation_images:1
args:validation_steps:10000000000000000000
args:num_eval_images:4
args:eval_dataset_id:None
args:validation_num_inference_steps:30
args:validation_resolution:1024
args:validation_noise_scheduler:euler
args:validation_disable_unconditional:False
args:disable_compel:False
args:enable_watermark:False
args:mixed_precision:bf16
args:local_rank:0
args:enable_xformers_memory_efficient_attention:True
args:set_grads_to_none:True
args:noise_offset:0.1
args:noise_offset_probability:0.25
args:validation_guidance:7.5
args:validation_guidance_rescale:0.0
args:validation_randomize:False
args:validation_seed:42
args:fully_unload_text_encoder:False
args:freeze_encoder_before:12
args:freeze_encoder_after:17
args:freeze_encoder_strategy:after
args:freeze_unet_strategy:none
args:unet_attention_slice:False
args:print_filenames:False
args:print_sampler_statistics:False
args:metadata_update_interval:65
args:debug_aspect_buckets:False
args:debug_dataset_loader:False
args:freeze_encoder:True
args:save_text_encoder:True
args:text_encoder_limit:25
args:prepend_instance_prompt:False
args:only_instance_prompt:False
args:data_aesthetic_score:7.0
args:sdxl_refiner_uses_full_range:False
args:caption_dropout_probability:0.1
args:delete_unwanted_images:False
args:delete_problematic_images:False
args:offset_noise:False
args:lr_end:4e-7
args:i_know_what_i_am_doing:False

**Comment by bghira** [comment]
the text encoder training really isn't tested much, and i don't have much time to maintain that feature. if you'd like to submit a pull request to resolve the issue, i can review it for inclusion

**Comment by bghira** [comment]
in fact this one looks like it might just have been from adding stable diffusion 3 support. still, for any further issues it might take a while to resolve if they relate to eg. model quality issues.

**Comment by pzzmyc** [comment]
Pull request creation failed. Validation failed: must be a collaborator
