### ISSUE TITLE
[Feature Request] Support Hunyuan-DiT

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [bghira/SimpleTuner#492]
Hunyuan-DiT is a new image generation AI. Benchmarks show that it exceeds SD3 overall.
However, the model is relatively complex and uses a lot of VRAM for training. So I thought it would be nice to be able to train it with SimpleTuner.

https://github.com/Tencent/HunyuanDiT

**Comment by bghira** [comment]
yeah, it's very slow to inference with too. it takes about 2 minutes for 1 image on a macbook pro m3 max. it'll take me a while to get to this but if someone else wants to take a crack at it, be my guest

**Comment by sayakpaul** [comment]
`diffusers` supports Hunyuan: https://huggingface.co/docs/diffusers/main/en/api/pipelines/hunyuandit. It's not based on Recitifed Flows, though. So, you should be able to repurpose the other diffusion-based training utilities provided in this repository and create a Hunyuan trainer.

**Comment by bghira** [comment]
components that must be implemented in simpletuner for hunyuan DiT training:

- a `--hunyuan_dit` argment is added
- model_type gets updated to include hunyuan_dit value alongside sdxl, sd3, pixart_sigma, etc
- initial model loading for the trained transformer must be added or included alongside eg. pixart's loading, if the two are compatible and can be shared
- text embed caching then needs a hunyuan codepath added, which can probably be shared with pixart depending on how it expects the embeds to be used. for example, DeepFloyd's T5 embeds don't return the attn mask, they just encode the embeds with it. but PixArt Sigma requires the attn mask as an input to the transformer itself.
- i think the vae cache works just fine as-is
- checkpoint save/load should be enhanced to include the logic for hunyuan or share with pixart where appropriate
- any kind of specific loss augmentation - scaling, weighting, masking, must be added to the training loop if required
- documentation must be produced and included, eg. a quickstart guide w/ a functional dataset is required for all new models added

**Comment by sayakpaul** [comment]
@bghira I am happy to give you a hand in this as this is going to be beneficial I think. 

Would you mind creating some issues w.r.t the above plan and mention me there? I think it could be nice to divide the integration into smaller PRs and work towards getting them merged.

**Comment by bghira** [comment]
careful what you wish for: https://github.com/bghira/SimpleTuner/pull/524

**Comment by bghira** [comment]
closed due to @sayakpaul presumably departing the project
