### ISSUE TITLE
 DummyOptim is not an Optimizer

### ISSUE THREAD

**Issue by Laidawang** [bghira/SimpleTuner#495]
![image](https://github.com/bghira/SimpleTuner/assets/85244566/a31ca553-93e7-49cc-b6fd-26fbd3ff7bf5)
When I use single card training, I get the error DummyOptim is not an Optimizer
But when using multi-card training, the error disappears

**Comment by bghira** [comment]
you probably have deepspeed enabled

**Comment by Laidawang** [comment]
How do I force close it?

**Comment by bghira** [comment]
use `accelerate config default` i think to reset to defaults

**Comment by Laidawang** [comment]
works for me thank you so much

**Comment by Laidawang** [comment]
another question，I try fine-tuning sd3 with one A100(40G), and when the bs=40, it only consumed 20g of gpu memory, and when bs=80, it consumed 30g of gpu memory. This seems too little.

**Comment by bghira** [comment]
you might be making a lora. or using bitfit

**Comment by Laidawang** [comment]
yes, im using bitfit, can I turn it off？ Does this have any impact on the training of the model?

**Comment by bghira** [comment]
you can turn it off but might have to restart as the optimiser won't have the weights in its parameter list.

set USE_BITFIT=false

or just use bitfit and tune the biases and let us know how that goes, because non-bitfit full tuning really doesn't work too well.

**Comment by Laidawang** [comment]
Even if I cancel it, the memory cost is still very small, 40bs=33G

**Comment by Laidawang** [comment]
When I validate I get an error, is it possible to move the weight to the cpu to reduce the memory usage?
![image](https://github.com/bghira/SimpleTuner/assets/85244566/c43e5b7c-46b4-475f-88be-46dc1245d669)

**Comment by bghira** [comment]
i'm not getting that same error. is it for all validation prompts or just one or?
