### ISSUE TITLE
tensorboard support

### ISSUE THREAD

**Issue by Laidawang** [bghira/SimpleTuner#497]
Can you add support for tensorboard?

**Comment by twri** [comment]
It's already in the trainer.

```  --report_to REPORT_TO
                        The integration to report the results and logs to. Supported platforms are `"tensorboard"`
                        (default), `"wandb"` and `"comet_ml"`. Use `"all"` to report to all integrations.```

**Comment by bghira** [comment]
if it's not working, i'm not quite sure what to do about it. i've only ever used wandb.

**Comment by twri** [comment]
I tried it yesterday and it works but I don't use the wrapper bash scripts.

**Comment by bghira** [comment]
i mean, does it receive validation images too? that's the part i think isn't implemented.

**Comment by Laidawang** [comment]
I think it dont receive validation images，check the diffusers implementation https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sd3.py#L153

**Comment by sayakpaul** [comment]
Yeah we don't send the validation images to Tensorboard given it's used very little. But feel free to send over a PR if you think it's nice.
