### ISSUE TITLE
Feature request: Convert single sdxl safetensors to diffusers format using Kohya's SD scripts.

### ISSUE THREAD

**Issue by pzzmyc** [bghira/SimpleTuner#499]
I modified some code so that you only need to provide a single file path and an output path. After testing, it works well.
[sdxl_model_util.txt](https://github.com/user-attachments/files/15901140/sdxl_model_util.txt)

**Comment by bghira** [comment]
i'm not sure where this is supposed to go?

**Comment by sayakpaul** [comment]
What is the scope of this request? Could you elaborate more?

**Comment by bghira** [comment]
without any further information, no action can be taken
