### ISSUE TITLE
Should use vae.config.shift_factor in sd3 finetuning?

### ISSUE THREAD

**Issue by WeilunDai66** [bghira/SimpleTuner#500]
In diffusers StableDiffusion3Pipeline implementation, it uses latents = (latents / self.vae.config.scaling_factor) + self.vae.config.shift_factor before reconstruct pixel from noise. But I didn't see the vae shift_factor in any of the training scripts.
Did I miss something or could someone tell me whether the shift_factor needed in sd3 finetuning.

**Comment by bghira** [comment]
it's fixed at 3 for the 1024px model.
