### ISSUE TITLE
validation dtype error, cpubfloat16 vs gpu bfloat16

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#501]
When I validate I get an error, is it possible to move the weight to the cpu to reduce the memory usage?
![image](https://github.com/bghira/SimpleTuner/assets/85244566/c43e5b7c-46b4-475f-88be-46dc1245d669)

_Originally posted by @Laidawang in https://github.com/bghira/SimpleTuner/issues/495#issuecomment-2178319420_

**Comment by Laidawang** [comment]
it happens for all prompt，This is how to reproduce it，
1. `accelerate config default` you may need to rm the original config file.
2. `export USE_BITFIT=false` when MODEL_TYPE=full
3. `export TRAINING_NUM_PROCESSES=1
export TRAINING_NUM_MACHINES=1
export ACCELERATE_EXTRA_ARGS=""    `

**Comment by bghira** [comment]
can you check on master branch?

**Comment by Laidawang** [comment]
![image](https://github.com/bghira/SimpleTuner/assets/85244566/4e622256-6f01-45c6-95b7-97f469de5bd8)
the bug changes

**Comment by Laidawang** [comment]
![image](https://github.com/bghira/SimpleTuner/assets/85244566/16a1800f-9255-49d5-ab7f-5d99970a3707)
also add this to fix an importing bug

**Comment by bghira** [comment]
i really don't get why it's on two devices..

**Comment by Laidawang** [comment]
Can you reproduce this bug according to my settings?

**Comment by bghira** [comment]
unfortunately, i cannot reproduce the issue still. if you can figure out which line the item needs to be cast to the correct device/dtype, please let me know, and i will fix it.
