### ISSUE TITLE
TypeError: new(): invalid data type 'str'

### ISSUE THREAD

**Issue by pzzmyc** [bghira/SimpleTuner#502]
sorry, sir, there is another error. When training SDXL LoRA and setting both the learning rate and text encoder learning rate, it will result in a TypeError: new(): invalid data type 'str'.

![image](https://github.com/bghira/SimpleTuner/assets/43562427/6e0ae60b-9a10-4693-9360-a01998f07281)
![image](https://github.com/bghira/SimpleTuner/assets/43562427/396207a7-30da-4ddd-b907-6e7b2413d47d)

**Comment by bghira** [comment]
can you try wrapping that `args.learning_rate` like `float(args.learning_rate)` and test?

**Comment by pzzmyc** [comment]
> can you try wrapping that `args.learning_rate` like `float(args.learning_rate)` and test?

i tried ,its not work,
![image](https://github.com/bghira/SimpleTuner/assets/43562427/1b8637c8-ebdd-4535-b8d4-862f6fb3fa18)

**Comment by pzzmyc** [comment]
i tried ,it is nor work 
![image](https://github.com/bghira/SimpleTuner/assets/43562427/8d38fb0b-68a6-45d5-9650-ef3290854b7e)

**Comment by bghira** [comment]
it looks like my text encoder training lora implementation is outdated vs what the diffusers upstream has. do you want to try and update it?

**Comment by bghira** [comment]
ok, without any interest in fixing the text encoder training, i will simply close this for now.
