### ISSUE TITLE
OUTPUT_DIR variable in sdxl_env.sh is ignored

### ISSUE THREAD

**Issue by roperi** [bghira/SimpleTuner#51]
If you configure this:
```
### sdxl_env.sh
# Location of training data.
export BASE_DIR="/workspace/SimpleTuner/"
export INSTANCE_DIR="${BASE_DIR}/input/"
export OUTPUT_DIR="${BASE_DIR}/models"
```

Model is saved in :
`/notebooks/datasets/models/ptx0-xltest/`

^ Seems this path was hardcoded.

**Comment by bghira** [comment]
on the release branch? i have not yet merged the fix into there.

**Comment by bghira** [comment]
v0.2.3 is published now, which includes that and several other changes incl storing the trainer state in the ckpt dirs.

please give that a try.
