### ISSUE TITLE
SD3 cannot be trained

### ISSUE THREAD

**Issue by pjrpjr** [bghira/SimpleTuner#518]
I am a windows system and use WSL to operate Ubuntu.

(.venv) root@DESKTOP-DVFFB09:/mnt/host/d/projects/SimpleTuner# bash train_sdxl.sh
sdxl-env.sh.example: line 2: $'\r': command not found
sdxl-env.sh.example: line 7: $'\r': command not found
sdxl-env.sh.example: line 14: $'\r': command not found
sdxl-env.sh.example: line 19: $'\r': command not found
sdxl-env.sh.example: line 24: $'\r': command not found
sdxl-env.sh.example: line 36: $'\r': command not found
sdxl-env.sh.example: line 39: $'\r': command not found
sdxl-env.sh.example: line 45: $'\r': command not found
sdxl-env.sh.example: line 49: $'\r': command not found
sdxl-env.sh.example: line 54: $'\r': command not found
sdxl-env.sh.example: line 59: $'\r': command not found
sdxl-env.sh.example: line 64: $'\r': command not found
sdxl-env.sh.example: line 76: $'\r': command not found
sdxl-env.sh.example: line 87: $'\r': command not found
sdxl-env.sh.example: line 90: $'\r': command not found
sdxl-env.sh.example: line 105: $'\r': command not found
sdxl-env.sh.example: line 106: $'\r': command not found
sdxl-env.sh.example: line 112: $'\r': command not found
sdxl-env.sh.example: line 120: $'\r': command not found
sdxl-env.sh.example: line 125: $'\r': command not found
sdxl-env.sh.example: line 128: $'\r': command not found
sdxl-env.sh.example: line 133: $'\r': command not found
sdxl-env.sh.example: line 138: $'\r': command not found
sdxl-env.sh.example: line 142: $'\r': command not found
sdxl-env.sh.example: line 145: $'\r': command not found
sdxl-env.sh.example: line 149: $'\r': command not found
sdxl-env.sh.example: line 153: $'\r': command not found
sdxl-env.sh.example: line 160: $'\r': command not found
sdxl-env.sh.example: line 161: $'\r': command not found
sdxl-env.sh.example: line 166: $'\r': command not found
sdxl-env.sh.example: line 171: $'\r': command not found
sdxl-env.sh.example: line 182: $'\r': command not found
sdxl-env.sh.example: line 186: $'\r': command not found
sdxl-env.sh.example: line 192: $'\r': command not found
sdxl-env.sh.example: line 193: $'\r': command not found
sdxl-env.sh.example: line 196: $'\r': command not found
sdxl-env.sh.example: line 200: $'\r': command not found
sdxl-env.sh.example: line 205: $'\r': command not found
sdxl-env.sh.example: line 210: $'\r': command not found
sdxl-env.sh: line 2: $'\r': command not found
sdxl-env.sh: line 7: $'\r': command not found
sdxl-env.sh: line 14: $'\r': command not found
sdxl-env.sh: line 19: $'\r': command not found
sdxl-env.sh: line 24: $'\r': command not found
sdxl-env.sh: line 36: $'\r': command not found
sdxl-env.sh: line 39: $'\r': command not found
sdxl-env.sh: line 45: $'\r': command not found
sdxl-env.sh: line 49: $'\r': command not found
sdxl-env.sh: line 54: $'\r': command not found
sdxl-env.sh: line 59: $'\r': command not found
sdxl-env.sh: line 64: $'\r': command not found
sdxl-env.sh: line 76: $'\r': command not found
sdxl-env.sh: line 87: $'\r': command not found
sdxl-env.sh: line 90: $'\r': command not found
sdxl-env.sh: line 105: $'\r': command not found
sdxl-env.sh: line 106: $'\r': command not found
sdxl-env.sh: line 112: $'\r': command not found
sdxl-env.sh: line 120: $'\r': command not found
sdxl-env.sh: line 125: $'\r': command not found
sdxl-env.sh: line 128: $'\r': command not found
sdxl-env.sh: line 133: $'\r': command not found
sdxl-env.sh: line 138: $'\r': command not found
sdxl-env.sh: line 142: $'\r': command not found
sdxl-env.sh: line 145: $'\r': command not found
sdxl-env.sh: line 149: $'\r': command not found
sdxl-env.sh: line 153: $'\r': command not found
sdxl-env.sh: line 160: $'\r': command not found
sdxl-env.sh: line 161: $'\r': command not found
sdxl-env.sh: line 166: $'\r': command not found
sdxl-env.sh: line 171: $'\r': command not found
sdxl-env.sh: line 182: $'\r': command not found
sdxl-env.sh: line 186: $'\r': command not found
sdxl-env.sh: line 192: $'\r': command not found
sdxl-env.sh: line 193: $'\r': command not found
sdxl-env.sh: line 196: $'\r': command not found
sdxl-env.sh: line 200: $'\r': command not found
sdxl-env.sh: line 205: $'\r': command not found
sdxl-env.sh: line 210: $'\r': command not found
Unknown optimizer requested: adamw8bit

**Comment by bghira** [comment]
I would suggest not using Windows for ML.
