### ISSUE TITLE
 No images were discovered by the bucket manager in the dataset ( continue from #545 )

### ISSUE THREAD

**Issue by pvp-by** [bghira/SimpleTuner#548]
On the recommendation @bghira create new issue, from the continuation of issue #545

I added an archive with my files and the structure of the whole `bugfix/bucket-search` branch.
There are not many of them and there is no secrecy in the images.
[bucket.tar.gz](https://github.com/user-attachments/files/16042214/bucket.tar.gz)

png+txt in one folder (train)

**Comment by bghira** [comment]
this is happening because `TRAIN_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS` is a greater value that the number of samples in the set (10)
