### ISSUE TITLE
2 Multi GPU related bugs with fix

### ISSUE THREAD

**Issue by LeroyDaydreamer** [bghira/SimpleTuner#566]
Hi, 
I suggest the following two fixes in train_sd21.py to prevent crashes when multiple GPUs are present.

1. To prevent "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"
Line 1007:
```
    initial_msg += f"\n-  Num batches = {total_num_batches}, unet dtype: `{unet.dtype}`"
```
Fix:
```
    unet_dtype = unet.module.dtype if isinstance(unet, nn.parallel.DistributedDataParallel) else unet.dtype
    initial_msg += f"\n-  Num batches = {total_num_batches}, unet dtype: `{unet_dtype}`"
```
This requires a new import:
```
import torch.nn as nn
```

2. To prevent AttributeError: 'DistributedDataParallel' object has no attribute 'dtype'
Line 1388:
```
                    training_logger.debug(f"Stepping EMA unet forward")
```
Fix:		
```
	  	   training_logger.debug(f"Stepping EMA unet forward")
		  # Ensure that the EMA model is on the correct device
                   ema_model.to(device=accelerator.device, dtype=weight_dtype)
```

**Comment by bghira** [comment]
that script really needs a lot of updates. or to be eliminated. can i ask what you're training with that?

**Comment by bghira** [comment]
see #568, everything is reorganised to use the one script now. also, please let me know if you see any problems. it's easier to maintain this way, as the fixes apply everywhere at once.
