### ISSUE TITLE
While fine-tuning Stable Diffusion 3 with LoRA by the instruction of documentation/quickstart/SD3.md, train.sh file is missing.

### ISSUE THREAD

**Issue by xingyouxin** [bghira/SimpleTuner#572]
Hello everyone,

While fine-tuning Stable Diffusion 3 with LoRA by the instruction of documentation/quickstart/SD3.md, I find the train.sh file is missing. 

With the instruction of SD3.md, I cloned the branch of release. However, the train.sh file is missing. So is there any way to solve the problem? Thank you very much.

**Comment by bghira** [comment]
you can use the release branch documentation as well, which has the old layout. the project is in a transition to a new layout. i would recommend actually jumping to the main branch for now.

**Comment by bghira** [comment]
though it's working well enough, i merged the two. you can `git pull` or switch to main branch.

**Comment by xingyouxin** [comment]
Thank you very much!
