### ISSUE TITLE
How to train 900M PixArt Sigma  ?

### ISSUE THREAD

**Issue by kingkong135** [bghira/SimpleTuner#580]
I have a question, I see the Pixart Sigma train by default is 600M, I want to try finetune with 900M PixArt Sigma like [PixArt Sigma 900M: Enhanced Text-to-Image Model
](https://civitai.com/models/573014?modelVersionId=638760)

**Comment by bghira** [comment]
you'll need to have a version from hugging face hub. and then just use that as the MODEL_NAME, eg. `terminusresearch/pixart-900m-1024-v0.6`
