### ISSUE TITLE
AuraFlow

### ISSUE THREAD

**Issue by janzd** [bghira/SimpleTuner#585]
I just want to ask about AuraFlow. It seems that the checkpoint `auradiffusion/auradiffusion-v0.1a0` listed in the config for AuraFlow doesn't exist and when I searched for some info about it, it said that it's not public yet and will be released soon. I was wondering if there was a pre-release somewhere or if you just had early access to it.

**Comment by bghira** [comment]
you will have to use `fal/AuraFlow` but the model currently only supports square crops and requires a lot of resources to train.

**Comment by janzd** [comment]
I got back to trying it and managed to run it. I know that the readme says that LoRA is the only viable option now, but I tried full model finetuning and I managed to run that but I wasn't able to run LoRA.

This is what I get. Any idea what the cause might be? I have diffusers on the `0.30.0.dev0` version.
```
2024-07-25 02:57:41,086 [INFO] (__main__) Using LoRA training mode.
'AuraFlowTransformer2DModel' object has no attribute 'add_adapter'
Traceback (most recent call last):
  File "/data/src/SimpleTuner/train.py", line 2473, in <module>
    main()
  File "/data/src/SimpleTuner/train.py", line 675, in main
    transformer.add_adapter(transformer_lora_config)
  File "/data/miniconda3/envs/simpletuner/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 151, in __getattr__
    return super().__getattr__(name)
  File "/data/miniconda3/envs/simpletuner/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AuraFlowTransformer2DModel' object has no attribute 'add_adapter'
```

**Comment by bghira** [comment]
you need the special diffusers branch mentioned in the quickstart guide

**Comment by bghira** [comment]
at this point i would give up on auraflow, it's got some core implementation issues and they've not been fixed by Simo. i have considered simply removing it from the trainer, as it falls apart with most attempts of training it.

**Comment by janzd** [comment]
Oh, I missed that there was an AuraFlow page in quickstart guides. Thanks!

I see. I was wondering what it's like but I don't really need it now either.
By falling apart, do you mean like completely failing and starting to generate rubbish?
I tried full model training on a dataset of like 50k characters in a pretty similar pose but I messed up the learning rate. However, it was still pretty close to the intended result, but the image was kinda smudgy, which I thought might have been cause by me messing up the learning rate.

**Comment by bghira** [comment]
![image](https://github.com/user-attachments/assets/dca06d1c-e4ea-419d-af30-505ebd0dff37)

**Comment by janzd** [comment]
ic, that looks similar to my result
thanks for sharing!

**Comment by bghira** [comment]
you're welcome. this is due to fundamental issues with the model's architectural implementation.

**Comment by ka-de** [comment]
> you're welcome. this is due to fundamental issues with the model's architectural implementation.

Maybe give [0.2](https://huggingface.co/fal/AuraFlow-v0.2) a try? It just came out.

**Comment by bghira** [comment]
it's the same architecture, same problems, same massive VRAM consumption
