### ISSUE TITLE
[caption_strategy] CSV tagging file with columns for image paths and captions

### ISSUE THREAD

**Issue by CanvaChen** [bghira/SimpleTuner#594]
After tagging, I saved the data as a CSV file with two columns: one for image paths and another for captions. How do I configure multidatabackend.json so that the training process can read the images and captions recorded in the file?

**Comment by bghira** [comment]
quite honestly, you would be better off writing image.txt file with the caption right next to image.png

it works much more quickly than loading these captions from dataframes

**Comment by bghira** [comment]
it's supported by the parquet backend. but that is not compatible with the json backend. you have to put together a full metadata file with filename, caption, width, height properties. and it is slow.

**Comment by bghira** [comment]
just the subtree, eg. without `instance_data_root` as a prefix.
