### ISSUE TITLE
Consulting

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#606]
Hey, do you by any chance offer consulting for training? We're working on a product that's a bit outside our technical abilities and I think you could help.

Apologies for opening a ticket; couldn't find your contact info elsewhere.

**Comment by blu3nh** [comment]
Hi.
bghira let me know you're interested in training help?

You can reach me on discord, via: _caith
I'll also send you an email, in case you prefer that type of communication.

With kind regards,
Caith

**Comment by komninoschatzipapas** [comment]
> _caith

I just sent you a friend request. Thanks a lot @bghira
