### ISSUE TITLE
FLUX LoRA Training: Got error after completion "'NoneType' object has no attribute 'peft_config'"

### ISSUE THREAD

**Issue by billnye2** [bghira/SimpleTuner#627]
Hello,

Got this error after training completed:

```python
2024-08-04 07:57:24,948 [INFO] (__main__) Exiting training loop. Beginning model unwind at epoch 250, step 500
'NoneType' object has no attribute 'peft_config'
Traceback (most recent call last):
  File "/content/SimpleTuner/train.py", line 2651, in <module>
    main()
  File "/content/SimpleTuner/train.py", line 2375, in main
    get_peft_model_state_dict(unet)
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py", line 71, in get_peft_model_state_dict
    config = model.peft_config[adapter_name]
AttributeError: 'NoneType' object has no attribute 'peft_config'
```

Thank you

**Comment by leonary** [comment]
```
Epoch 1/150, Steps:   0%|                                                                            | 0/150 [00:00<?, ?it/s]The size of tensor a (4) must match the size of tensor b (16) at non-singleton dimension 1
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/train.py", line 2651, in <module>
    main()
  File "/root/autodl-tmp/SimpleTuner/train.py", line 1818, in main
    noisy_latents = (
RuntimeError: The size of tensor a (4) must match the size of tensor b (16) at non-singleton dimension 1
```

@bghira Please also help me with my problem. I can't start training. Lora training of Flux-dev. Thanks a lot.

**Comment by leonary** [comment]
> Hello,
> 
> Got this error after training completed:
Hi, it looks like the author's train.py is missing something.
First you need to add from helpers.models.flux.pipeline import FluxPipeline to the first line of train.py, then around line 2368, find
if "lora" in args.model_type:
if args.sd3 or args.pixart_sigma:
transformer_lora_layers = convert_state_dict_to_diffusers(
get_peft_model_state_dict(transformer)
)
Change this part of "if args.sd3 or args.pixart_sigma:"
to: "if args.sd3 or args.pixart_sigma or args.flux:"
Now your model can be saved normally.

**Comment by rdcoder33** [comment]
> Hello,
> 
> Got this error after training completed:
> 
> ```python
> 2024-08-04 07:57:24,948 [INFO] (__main__) Exiting training loop. Beginning model unwind at epoch 250, step 500
> 'NoneType' object has no attribute 'peft_config'
> Traceback (most recent call last):
>   File "/content/SimpleTuner/train.py", line 2651, in <module>
>     main()
>   File "/content/SimpleTuner/train.py", line 2375, in main
>     get_peft_model_state_dict(unet)
>   File "/usr/local/lib/python3.10/dist-packages/peft/utils/save_and_load.py", line 71, in get_peft_model_state_dict
>     config = model.peft_config[adapter_name]
> AttributeError: 'NoneType' object has no attribute 'peft_config'
> ```
> 
> Thank you

Have you tried 

`pip install peft`

**Comment by bghira** [comment]
likely it needs a newer version of diffusers there

**Comment by bghira** [comment]
but also i never got to the actual end of training yet and there could be a bug at the emd of the universe

**Comment by rdcoder33** [comment]
Hi @bghira Thanks for working so hard with flux.

What were your test results? I am training on A100 a style lora 16 rank with lr 5e-6 and it's not training at all. All validation & unconditional images are identical even after 3000 steps. What's crazier is that the loss has actually increasing.

My dataset only has 300 images. Do I need more?

**Comment by bghira** [comment]
that's a really high learning rate for a 12B model. that would be used for maybe SDXL or SD 1.5.. and also, you might want to try inferencing with the adapter on its own, eg. outside of the trainer, which is how I tested mine. not sure about the validations yet, i assumed they would just work.

**Comment by rdcoder33** [comment]
> that's a really high learning rate for a 12B model. that would be used for maybe SDXL or SD 1.5.. and also, you might want to try inferencing with the adapter on its own, eg. outside of the trainer, which is how I tested mine. not sure about the validations yet, I assumed they would just work.

Yeah, the high lr was on purpose to see if its training I started with 8e-7. Is there any guide on how to use the Lora adapter with flux?

It's not working with default ComfyUI workflow:

```
lora key not loaded: transformer.single_transformer_blocks.0.attn.to_k.lora_B.weight
lora key not loaded: transformer.single_transformer_blocks.0.attn.to_q.lora_A.weight
lora key not loaded: transformer.single_transformer_blocks.0.attn.to_q.lora_B.weight
lora key not loaded: transformer.single_transformer_blocks.0.attn.to_v.lora_A.weight
lora key not loaded: transformer.single_transformer_blocks.0.attn.to_v.lora_B.weight
lora key not loaded: transformer.single_transformer_blocks.1.attn.to_k.lora_A.weight
lora key not loaded: transformer.single_transformer_blocks.1.attn.to_k.lora_B.weight
lora key not loaded: transformer.single_transformer_blocks.1.attn.to_q.lora_A.weight
lora key not loaded: transformer.single_transformer_blocks.1.attn.to_q.lora_B.weight
lora key not loaded: transformer.single_transformer_blocks.1.attn.to_v.lora_A.weight
```

**Comment by bghira** [comment]
probably because ComfyUI doesn't support them yet. open an issue there, or use Diffusers
