### ISSUE TITLE
A strange error train.py: error: argument --model_type: invalid choice: 'lora\r' 

### ISSUE THREAD

**Issue by pzc163** [bghira/SimpleTuner#632]
I don't know why, but when I run the bash train.sh script after setting up all the training parameters in config.env, I get the following series of very strange errors.So all the parameters have \r strange symbols at the end of them, why is that?

train.py: error: argument --model_type: invalid choice: 'lora\r' (choose from 'full', 'lora', 'deepfloyd-full', 'deepfloyd-lora', 'deepfloyd-stage2', 'deepfloyd-stage2-lora')
Traceback (most recent call last):
  File "/workspace/miniconda3/envs/SimpleTuner/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/miniconda3/envs/SimpleTuner/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/workspace/miniconda3/envs/SimpleTuner/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/workspace/miniconda3/envs/SimpleTuner/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/miniconda3/envs/SimpleTuner/bin/python', 'train.py', '--model_type=lora\r', '--pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev\r', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=2\r', '--resume_from_checkpoint=latest\r', '--snr_gamma=5\r', '--data_backend_config=config/multidatabackend.json', '--num_train_epochs=10\r', '--max_train_steps=30000\r', '--metadata_update_interval=65\r', '--use_8bit_adam', '--learning_rate=1e-4', '--lr_scheduler=cosine\r', '--seed', '42\r', '--lr_warmup_steps=1000\r', '--output_dir=/workspace/output\r', '--inference_scheduler_timestep_spacing=trailing\r', '--training_scheduler_timestep_spacing=trailing\r', '--report_to=wandb\r', '--mixed_precision=bf16', 'lora_rank=64\r', '--train_batch=4\r', '--max_workers=32\r', '--read_batch_size=25\r', '--write_batch_size=64\r', '--caption_dropout_probability=0.1\r', '--torch_num_threads=8\r', '--image_processing_batch_size=32\r', '--vae_batch_size=12\r', '--validation_prompt=ethnographic photography of teddy bear at a picnic\r', '--num_validation_images=1', '--validation_num_inference_steps=30\r', '--validation_seed=42\r', '--minimum_image_size=1024\r\r', '--resolution=1024\r', '--validation_resolution=1024\r\r', '--resolution_type=pixel\r', '--checkpointing_steps=150\r', '--checkpoints_total_limit=2\r', '--validation_steps=100\r', '--tracker_run_name=simpletuner-FLUX\r', '--tracker_project_name=LittleTinies-FLUX-lora\r', '--validation_guidance=7.5\r', '--validation_guidance_rescale=0.0\r', '--validation_negative_prompt=blurry, cropped, ugly\r']' returned non-zero exit status 2.
(SimpleTuner) root@16932722ad66:/workspace/SimpleTuner#

**Comment by bghira** [comment]
is it like some windows thing?

**Comment by pzc163** [comment]
its a windows edit error, i have figure out, but when load FLUX.1-dev model loacally, here is another error,

![image](https://github.com/user-attachments/assets/8c20e888-d3da-47e0-8842-46f04a6032ab)

below is my multidatabackend.json setting, is there any mistake with multidatabackend.json setting?
![image](https://github.com/user-attachments/assets/96c80cb0-4b3f-4a93-a031-2c12c7c98f70)

**Comment by pzc163** [comment]
strange error has been figure out, but when load flux.1-dev model locally,there is another error come out！  
![image](https://github.com/user-attachments/assets/e86c8b06-ee46-40d5-9079-88a8067a0b16)

**Comment by pzc163** [comment]
strange error has been figure out, but when load flux.1-dev model locally,there is another error come out！
RuntimeError: The size of tensor a (4) must match the size of tensor b (16) at non-singleton dimension 1
![image](https://github.com/user-attachments/assets/1c24d624-8811-4eec-88b4-919f81244be3)

**Comment by quzopl** [comment]
@pzc163 u need change batch from 4 to 1

**Comment by bghira** [comment]
that should be resolved on main, please check

**Comment by pzc163** [comment]
thanks It began to training，but in validation part，there are still some error
![image](https://github.com/user-attachments/assets/a37ec436-2964-418b-8410-77c69b773554)

**Comment by bghira** [comment]
that was also fixed in the main branch. are you sure you're on the latest?
