### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text_encoders'

### ISSUE THREAD

**Issue by lekima** [bghira/SimpleTuner#648]
I've been trying to train a Kolors LoRA.
Everything worked well but after pulling the new updates today:

1. My whole system (Win11) becomes extremely sluggish during the `Discovering cache objects...` step (my dataset is 40 1024x1024 images; PC spec is 4080 16GB GPU, 64GB RAM and 7950x3d CPU)

2. I got the warning `xformers is incompatible with this model type`, is this expected?

3. I got an error during the `Unloading text encoder` step.

```
2024-08-06 06:59:20,208 [INFO] (__main__) Unloading text encoders, as they are not being trained.
'NoneType' object has no attribute 'text_encoders'
Traceback (most recent call last):
  File "/mnt/c/users/minh/git/simpletuner/train.py", line 2725, in <module>
    main()
  File "/mnt/c/users/minh/git/simpletuner/train.py", line 952, in main
    prompt_handler.text_encoders = []
AttributeError: 'NoneType' object has no attribute 'text_encoders'
```

Here is my launch command
```
accelerate launch --mixed_precision=bf16 train.py --model_type=lora --kolors --pretrained_model_name_or_path=models/Kolors --enable_xformers_memory_efficient_attention --allow_tf32 --gradient_checkpointing --set_grads_to_none --gradient_accumulation_steps=1 --seed=19980818 --train_batch_size=1 --max_train_steps=2000 --num_train_epochs=0 --adam_bfloat16 --learning_rate=2e-5 --lr_scheduler=polynomial --lr_warmup_steps=100 --use_ema --lora_rank=4 --lora_alpha=1 --snr_gamma=5 --offset_noise --noise_offset=0.03 --caption_dropout_probability=0.3 --data_backend_config=datasets/multidatabackend.json --output_dir=output --checkpoints_total_limit=50 --checkpointing_steps=100 --validation_steps=100 --validation_prompt="prompt" --num_validation_images=1 --validation_disable_unconditional --validation_resolution=1024 --validation_noise_scheduler=euler-a --validation_num_inference_steps=50 --validation_guidance=5.0 --tracker_run_name=kolors-lora --tracker_project_name=kolors-lora
```

Here is the content of my `multidatabackend.json` file
```
[
  {
    "id": "dataset_name",
    "type": "local",
    "crop": true,
    "crop_aspect": "square",
    "crop_style": "center",
    "resolution": 1.0,
    "minimum_image_size": 1.0,
    "maximum_image_size": 1.0,
    "target_downsample_size": 1.0,
    "resolution_type": "area",
    "cache_dir_vae": "/path",
    "instance_data_dir": "/path",
    "disabled": false,
    "skip_file_discovery": "",
    "caption_strategy": "textfile",
    "metadata_backend": "json",
    "repeats": 5
  },
  {
    "id": "text-embeds",
    "type": "local",
    "dataset_type": "text_embeds",
    "default": true,
    "cache_dir": "/path",
    "disabled": false,
    "write_batch_size": 128
  }
]
```

**Comment by bghira** [comment]
ah - yes! i've overhauled some of the safety checks to be more conservative, but easier to expand or understand.

you can confirm Kolors works properly with Xformers? i will enable that for this.

for these changes you can use the `bugfix/quanto-lora-loading` branch

for the slowdown, i'm really not sure, i don't use windows. i think there is some funnyness with performance on there for shared filesystems in WSL.

**Comment by lekima** [comment]
> you can confirm Kolors works properly with Xformers? i will enable that for this.
apologies, I just didn't recall seeing the warning in the previous training rounds. Just noticed it just now due to the other error blocking the training. Hence I just want to confirm with you whether this is expected and I should not use xformers with Kolors. 😅 

(I did try to train Kolors using other scripts and look like many of them don't have xformers enabled hence I guess it won't work indeed)

> for these changes you can use the `bugfix/quanto-lora-loading` branch
thanks a lot for the quick fix, will give this a try and report back 🙏

> for the slowdown, i'm really not sure, i don't use windows. i think there is some funnyness with performance on there for shared filesystems in WSL.
I see, yes probably due to WSL, not a big deal imo, thank you for the info.

**Comment by bghira** [comment]
if it isn't too much work i would love some notes on setting up WSL2 for simpletuner and you could even open a pull request to the /documentation folder?

**Comment by bghira** [comment]
i will close this as it is now solved in main. thank you for the report!

**Comment by lekima** [comment]
> if it isn't too much work i would love some notes on setting up WSL2 for simpletuner and you could even open a pull request to the /documentation folder?

Yes I can give it a shot, will need a bit of time to test and document the steps from scratch to make sure it's working fine

**Comment by lekima** [comment]
> i will close this as it is now solved in main. thank you for the report!

Confirmed the issue is resolved! Thank you so much!
