### ISSUE TITLE
WandB times out and seems to prevent training when blocked by firewall

### ISSUE THREAD

**Issue by chongxian** [bghira/SimpleTuner#651]
when I follow the FLUX.md to set the args ,but the train always stop,because the error:

 (urllib3.connectionpool) Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/4504800232407040/envelope/
![image](https://github.com/user-attachments/assets/ff9cb9f5-881d-4d79-b663-63615e79644d)

how can I do to handle the issue,thanks for your reply

**Comment by Carolinabanana** [comment]
The HF repo for Flux Dev requires you to have an HF account that's accessed it, then login in with that token.

Alternatively, change the MODEL_NAME to ChuckMcSneed/FLUX.1-dev which is an ungated clone.

**Comment by bghira** [comment]
wow, flashback to the year 2002 - it's been a while since i've delt with proxies. anyone else remember Squid?

you might want to check whether running `wandb offline` helps. it will disable Weights & Biases.

there's otherwise not much reason for it to try connecting to the network at that point, training is actually beginning.

**Comment by bghira** [comment]
this was fixed by your newer PR, i think?

**Comment by chongxian** [comment]
> this was fixed by your newer PR, i think?

my PR just fix the issue about load kolors, this bug I haven't solved yet

**Comment by bghira** [comment]
this one might be wandb. try `wandb disable` before running `bash train.sh`

**Comment by chongxian** [comment]
> this one might be wandb. try `wandb disable` before running `bash train.sh`

if I set the wandb offline or wandb disabled , the error is also happen when I train the lora of the flux model, but it is work when I finetune the kolors model,but now my solution is to comment out all code about wandb

**Comment by bghira** [comment]
no need, just remove the --report-to=wandb
