### ISSUE TITLE
Error no file named pytorch_model.fp16.bin, model.fp16.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ../models/Kolors

### ISSUE THREAD

**Issue by lekima** [bghira/SimpleTuner#665]
Hi, after pulling the updates, I got this error during the `Loading ChatGLM language model from ../models/Kolors/text_encoder..` step.

`Error no file named pytorch_model.fp16.bin, model.fp16.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ../models/Kolors.`

The directory is correct and I can train ok yesterday. Below is the content of Kolors text_encoder folder.
Understand that it cannot find the files listed above, but these files don't exist in Kolors repo, and this worked fine before.

![Screenshot 2024-08-07 at 14 58 10](https://github.com/user-attachments/assets/7c180186-274e-40c8-857d-e0b7e850bc6a)

**Comment by bghira** [comment]
you have to follow the original naming convention for kolors. they have `.fp16` in the name there

**Comment by bghira** [comment]
oh. use the `kolors-diffusers` one..

**Comment by bghira** [comment]
yesterday the proper path wasn't being respected for kolors, and now it is - so the path you provided i guess wouldn't have worked before either. you should set it to `kwai-kolors/kolors-diffusers` again

**Comment by lekima** [comment]
@bghira thank you, I just switched to `kolors-diffusers` but now I encounter another error

```
2024-08-07 08:28:30,646 [INFO] (__main__) Loading U-net..
An error occurred while trying to fetch ../models/Kolors-diffusers: Error no file named diffusion_pytorch_model.safetensors found in directory ../models/Kolors-diffusers.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Error no file named diffusion_pytorch_model.bin found in directory ../models/Kolors-diffusers.
Traceback (most recent call last):
  File "/workspace/jupyter_notebooks/SimpleTuner/train.py", line 2750, in <module>
    main()
  File "/workspace/jupyter_notebooks/SimpleTuner/train.py", line 811, in main
    unet = UNet2DConditionModel.from_pretrained(
  File "/workspace/jupyter_notebooks/SimpleTuner/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/workspace/jupyter_notebooks/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 713, in from_pretrained
    model_file = _get_model_file(
  File "/workspace/jupyter_notebooks/SimpleTuner/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/workspace/jupyter_notebooks/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/utils/hub_utils.py", line 310, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory ../models/Kolors-diffusers.
```

**Comment by lekima** [comment]
@bghira If you check the [kolors-diffusers](https://huggingface.co/Kwai-Kolors/Kolors-diffusers/tree/main) repo, this `diffusion_pytorch_model.bin` file isn't there either

**Comment by lekima** [comment]
I did multiple training rounds very recently and there were no issues, the old path worked

**Comment by bghira** [comment]
they require the fp16 variant be used. so try --variant=fp16

**Comment by lekima** [comment]
thank you! Will give this a try

**Comment by lekima** [comment]
@bghira hi, I tried using the fp16 flag but now another error unfortunately, could you please help take a look if possible? 🙏

```
An error occurred while trying to fetch madebyollin/sdxl-vae-fp16-fix: madebyollin/sdxl-vae-fp16-fix does not appear to have a file named diffusion_pytorch_model.fp16.safetensors.
```

**Comment by bghira** [comment]
probably provide the `--pretrained_vae_model_name_or_path=kwai-kolors/kolors-diffusers`

**Comment by bghira** [comment]
the situation is explained above really - the files need `.fp16.` in the name and the Kolors repo is weird, in that it has **only** these files. your local version didn't have it - not sure why. but it's a bit outside of the scope of the issue tracker here unfortunately. they have set it up in a bit of an awkward way, i would open an issue with them and ask for consistency in their repo layout

**Comment by lekima** [comment]
`--pretrained_vae_model_name_or_path=kwai-kolors/kolors-diffusers` didn't help, same error unfortunately.

```An error occurred while trying to fetch madebyollin/sdxl-vae-fp16-fix: madebyollin/sdxl-vae-fp16-fix does not appear to have a file named diffusion_pytorch_model.fp16.safetensors.```

Understand that this is out of your scope, hence just want to follow up for the sake of visibility. Thank you!
