### ISSUE TITLE
bf16 error

### ISSUE THREAD

**Issue by fiona-lxd** [bghira/SimpleTuner#67]
Hi, I am trying to use this code for finetuning SDXL. However, when I set the mixed precision as bf16, it exits with error below:

Checkpoint 'latest' does not exist. Starting a new training run.

  0%|          | 0/625 [00:00<?, ?it/s]
Steps:   0%|          | 0/625 [00:00<?, ?it/s]08/30/2023 21:39:19 - DEBUG - __main__ - Starting into epoch: 0 (final epoch: 25)
Traceback (most recent call last):
  File "/workspace/train/train_sdxl.py", line 1388, in <module>
    main()
  File "/workspace/train/train_sdxl.py", line 1073, in main
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/accelerator.py", line 1683, in backward
    loss.backward(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected tensor for argument #1 'grad_output' to have the same type as tensor for argument #2 'weight'; but type CUDABFloat16Type does not equal torch.cuda.HalfTensor (while checking arguments for cudnn_convolution_backward_input)

Steps:   0%|          | 0/625 [00:14<?, ?it/s]

Can you help me on this issue?

**Comment by bghira** [comment]
what hardware is that on?

**Comment by fiona-lxd** [comment]
A100, python=3.9.12, pytorch=1.12.1

**Comment by bghira** [comment]
this project requires PyTorch 2.0.1

**Comment by bghira** [comment]
i have overhauled the `poetry` dependency list. please give that a try.
