### ISSUE TITLE
Error on saving Flux lora, Deepspeed missing CUDA_HOME

### ISSUE THREAD

**Issue by TheDuckingDuck** [bghira/SimpleTuner#672]
Currently the trainer crashes when saving Flux lora checkpoints due to cuda home missing for the newer deepspeed.
I'm on the latest main branch, with all the updated dependencies afaik.

Error:
>    raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)

**Comment by bghira** [comment]
i'm not sure i really have the bandwidth to look into this one, someone else with the equipment and ability to reproduce the issue might have to take a look, or, you might have to provide the solution

**Comment by TheDuckingDuck** [comment]
> i'm not sure i really have the bandwidth to look into this one, someone else with the equipment and ability to reproduce the issue might have to take a look, or, you might have to provide the solution

As far as I can tell, it might just be deepspeed changing, and adding it as a requirement. Even simply importing the latest package will throw the error in the current environment as installed by poetry.

Easiest solution is to install conda and make an environment that has cuda with `conda install nvidia/label/cuda-12.4.0::cuda-toolkit`, then activating that before you activate the regular venv.

**Comment by bghira** [comment]
no no, i really dislike conda :D

**Comment by bghira** [comment]
this was confirmed to be working on the main branch now. the train.sh script is updated to locate and rely on the nvidia libraries in the venv.
