### ISSUE TITLE
dockerfile is outdated and uses wrong cuda dependencies

### ISSUE THREAD

**Issue by bghira** [bghira/SimpleTuner#674]
@komninoschatzipapas can you look into this one?

**Comment by komninoschatzipapas** [comment]
> @komninoschatzipapas can you look into this one?

on it

**Comment by komninoschatzipapas** [comment]
#675

**Comment by bghira** [comment]
i have updated the train.sh to make use of the venv's version of nvidia libraries. can you test that maybe? thank you for the quick update

**Comment by komninoschatzipapas** [comment]
@bghira I think that's working correctly

```
root@42e8f2f94563:/workspace/SimpleTuner# ls .venv/lib/python3.10/site-packages/nvidia | col
__init__.py
cublas
cuda_cupti
cuda_nvrtc
cuda_runtime
cudnn
cufft
curand
cusolver
cusparse
nccl
nvjitlink
nvtx
```
