### ISSUE TITLE
Allow checkpoint save after N epochs

### ISSUE THREAD

**Issue by binitt** [bghira/SimpleTuner#687]
I think adding this option along with existing option: checkpointing_steps
will add value. 

Because mostly I would prefer to save and validate checkpoint after an epoch completion.

**Comment by bghira** [comment]
it is kind of a silly request, no? you know the number of steps in an epoch. i really dont want to have so many possible triggers for everything. it is complex enough

**Comment by binitt** [comment]
I have a different perspective on this. This feature is actually one of the most valuable ones for me in Kohya, as it helps me decide which checkpoint to select without having to wait for all the epochs/steps to complete. I was really excited when I discovered this new tool and thought it was great, but I was disappointed to find that this feature was missing. I believe that calculating steps from an epoch should be handled by the tool itself. For now, I'll continue using Kohya. Thank you for your efforts anyway.

**Comment by bghira** [comment]
that's why other options exist
