### ISSUE TITLE
[Feature Request] AdamWScheduleFree

### ISSUE THREAD

**Issue by ConsceIeratus** [bghira/SimpleTuner#695]
https://github.com/facebookresearch/schedule_free

**Comment by bghira** [comment]
it needs to be stochastic rounding compatible if we are adding new optims

**Comment by AmericanPresidentJimmyCarter** [comment]
Yeah, the current adamw is adapted for bf16 with some tricks (stochastic rounding and overflow register). To add a new adamw you would need to add similar trick and then test training to ensure that it works the same as training in float32.

In bfloat16 optims are pretty sensitive to rounding error and if you just use them as-is you will get subpar results.
