### ISSUE TITLE
LoRA loftq init stuck in a loop

### ISSUE THREAD

**Issue by twri** [bghira/SimpleTuner#709]
After commit fba126e that introduced loftq LoRA init trainer gets stuck in a infinite loop. Setting the init back to default resolves it. I've rebuilt the virtual environment with the latest using poetry. Also tried to install feat-support-optimum-quanto suggested in #700.

Any idea what I'm missing to make it work? I have possibly missed something obvious.

2024-08-10 18:48:58,888 [INFO] (__main__) Using LoRA training mode (rank=32)
2024-08-10 18:48:58,944 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
2024-08-10 18:48:59,646 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
2024-08-10 18:49:00,352 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
2024-08-10 18:49:01,048 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
2024-08-10 18:49:01,748 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
2024-08-10 18:49:02,445 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4
2024-08-10 18:49:03,134 [INFO] (root) Weight: (3072, 3072) | Rank: 32 | Num Iter: 1 | Num Bits: 4

**Comment by twri** [comment]
I think I understood why, loftq works only in combination with quantization.

**Comment by bghira** [comment]
nay, loftq is incompatible with quantisation because it is a form of its own quantisation

this is going through the weights and casting them to 4bit, by the looks of things.

**Comment by bghira** [comment]
it just takes a while but you can disable this with `--lora_init_method=default`

LoftQ was just used because it better approximates the standard deviation of the base model weights rather than a gaussian distribution which is harder to train into

**Comment by bghira** [comment]
it'll be mentioned in an update to the docs to enable loftq optionally, but i'll disable it for now, since we've learnt about more effective improvements to the training/sampling procedures.

**Comment by twri** [comment]
Yeah, give it a little bit more time and it completes.

I'm trying to figure out if you can have the gradients in fp32 or not. Like this:

export OPTIMIZER="prodigy"

export MIXED_PRECISION="bf16"
export PURE_BF16=true

export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --text_encoder_1_precision=no_change --text_encoder_2_precision=no_change"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --keep_vae_loaded"

export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --flux_lora_target=mmdit"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --lora_init_type=loftq"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --lora_rank=32"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --lora_alpha=32"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --max_grad_norm=1.0"

export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --base_model_default_dtype=fp32"
export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --gradient_precision=fp32"

export TRAINER_EXTRA_ARGS="${TRAINER_EXTRA_ARGS} --i_know_what_i_am_doing"

It errors out with this though: RuntimeError: dot : expected both vectors to have same dtype, but found Float and BFloat16
Setting gradients back to bf16 training works. Is this also expected?

**Comment by bghira** [comment]
the prodigy optimiser is especially picky about pretty much everything. it needs everything to be in the same dtype - at least if it's the same error I received earlier. try a different optim eg. adamw or maybe just need to rethink that functionality some more. it's really only needed if you have gradient accumulation steps enabled, and can be safely set to `unchanged` otherwise

**Comment by twri** [comment]
I just tested AdamW and that works so yeah, it's related to Prodigy. Thanks for the explanation and it makes sense.

**Comment by twri** [comment]
It seems to me that loftq with Prodigy (only tested this so far) got extremely stable, it learns but not much. Could be a issue with Prodigy and loftq. Will try adam too. I like stable but this might be too much, maybe one has to change Prodigy LR to something larger than the default of 0.5.

**Comment by bghira** [comment]
try using flux_lora_target=all+ffs

**Comment by twri** [comment]
Thanks. I'll do that. I'm doing a run on only the mmdit now with adam_bf16 and samples `--validation_guidance=3.0 --validation_guidance_real=3.0 --validation_guidance_rescale=0.0`. It was all muddy to begin with but I think samples are clearing up. Testing in Comfy at the same time with the adaptive guider.

Nice work to everybody in the team!
