### ISSUE TITLE
Flux lora training error : TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by BenDes21** [bghira/SimpleTuner#718]
Hi there,

I followed from a to z the quick start guide for flux lora training, but at the moment to launch the training with bash train.sh I got this error, anyone know where it's can come from ?  Thanks

<img width="921" alt="Untitled" src="https://github.com/user-attachments/assets/0bae6138-fb4c-461e-8dee-824a8b54ee7f">

**Comment by mhirki** [comment]
This looks like a duplicate of issue #710. You should try installing sentencepiece:
`pip install sentencepiece`

**Comment by BenDes21** [comment]
> This looks like a duplicate of issue #710. You should try installing sentencepiece: `pip install sentencepiece`

working! Thanks a lot

**Comment by bghira** [comment]
thanks, that is resolved in the main branch now.
