### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c cd SimpleTuner && python3 -m venv .venv && poetry install --no-root" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by protector131090** [bghira/SimpleTuner#728]
5 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 12)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "HUGGING_FACE_HUB_TOKEN") (line 50) - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "HUGGING_FACE_HUB_TOKEN") (line 51) - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "WANDB_TOKEN") (line 59)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "WANDB_TOKEN") (line 60)
Dockerfile:72
--------------------
  70 |     # Install SimpleTuner
  71 |     RUN pip3 install poetry
  72 | >>> RUN cd SimpleTuner && python3 -m venv .venv && poetry install --no-root
  73 |     RUN chmod +x SimpleTuner/train.sh
  74 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd SimpleTuner && python3 -m venv .venv && poetry install --no-root" did not complete successfully: exit code: 1

**Comment by bghira** [comment]
gentle ping @komninoschatzipapas for when you have a moment to look into this one 🙏

**Comment by komninoschatzipapas** [comment]
@protector131090 Can you show the lines before `ERROR: failed to solve: process "/bin/sh -c cd SimpleTuner && python3 -m venv .venv && poetry install --no-root" did not complete successfully: exit code: 1` so we can see where it's failing? Also, I'd like to know what command you're using to build this.

Regarding the `SecretsUsedInArgOrEnv` warnings, I like to bake everything into the image for convenience. However, it might make sense to move that code over to `docker-start.sh`. If you push an image with the envs set on a public Docker registry, other people will be able to see the env values.

I'll try to move that now, actually.

**Comment by komninoschatzipapas** [comment]
I just ran a build with `docker buildx build -f Dockerfile --platform linux/amd64 --output type=docker --provenance false` and it went through.

@bghira, we could save users this hassle by offering prebuilt images 

Check #732 for moving the ENVs.

**Comment by protector131090** [comment]
> @protector131090 Can you show the lines before `ERROR: failed to solve: process "/bin/sh -c cd SimpleTuner && python3 -m venv .venv && poetry install --no-root" did not complete successfully: exit code: 1` so we can see where it's failing? Also, I'd like to know what command you're using to build this.
> 
> Regarding the `SecretsUsedInArgOrEnv` warnings, I like to bake everything into the image for convenience. However, it might make sense to move that code over to `docker-start.sh`. If you push an image with the envs set on a public Docker registry, other people will be able to see the env values.
> 
> I'll try to move that now, actually.

after 5-th try it went through. but now im getting S:\SimpleTuner>docker run --gpus all -it -p 22:22 simpletuner
exec /start.sh: no such file or directory

S:\SimpleTuner>

**Comment by komninoschatzipapas** [comment]
> > @protector131090 Can you show the lines before `ERROR: failed to solve: process "/bin/sh -c cd SimpleTuner && python3 -m venv .venv && poetry install --no-root" did not complete successfully: exit code: 1` so we can see where it's failing? Also, I'd like to know what command you're using to build this.
> > Regarding the `SecretsUsedInArgOrEnv` warnings, I like to bake everything into the image for convenience. However, it might make sense to move that code over to `docker-start.sh`. If you push an image with the envs set on a public Docker registry, other people will be able to see the env values.
> > I'll try to move that now, actually.
> 
> after 5-th try it went through. but now im getting S:\SimpleTuner>docker run --gpus all -it -p 22:22 simpletuner exec /start.sh: no such file or directory
> 
> S:\SimpleTuner>

That's odd. Can you try rebuilding using the `buildx` command I shared above?

On my machine it runs just fine:
```
root@ubuntu-s-4vcpu-8gb-nyc3-01:~/simpletuner# docker run -it orionkomninos/simpletuner:latest
Exporting environment variables...
 * Starting OpenBSD Secure Shell server sshd                                                                                                                                                                                                                              [ OK ] 
HUGGING_FACE_HUB_TOKEN not set; skipping login
WANDB_TOKEN not set; skipping login
```

Please also check that you're on the latest version and haven't edited the `Dockerfile`. It really shouldn't try to execute `/start.sh` - our file is named `docker-start.sh`.

**Comment by protector131090** [comment]
> > > @protector131090 Can you show the lines before `ERROR: failed to solve: process "/bin/sh -c cd SimpleTuner && python3 -m venv .venv && poetry install --no-root" did not complete successfully: exit code: 1` so we can see where it's failing? Also, I'd like to know what command you're using to build this.
> > > Regarding the `SecretsUsedInArgOrEnv` warnings, I like to bake everything into the image for convenience. However, it might make sense to move that code over to `docker-start.sh`. If you push an image with the envs set on a public Docker registry, other people will be able to see the env values.
> > > I'll try to move that now, actually.
> > 
> > 
> > after 5-th try it went through. but now im getting S:\SimpleTuner>docker run --gpus all -it -p 22:22 simpletuner exec /start.sh: no such file or directory
> > S:\SimpleTuner>
> 
> That's odd. Can you try rebuilding using the `buildx` command I shared above?
> 
> On my machine it runs just fine:
> 
> ```
> root@ubuntu-s-4vcpu-8gb-nyc3-01:~/simpletuner# docker run -it orionkomninos/simpletuner:latest
> Exporting environment variables...
>  * Starting OpenBSD Secure Shell server sshd                                                                                                                                                                                                                              [ OK ] 
> HUGGING_FACE_HUB_TOKEN not set; skipping login
> WANDB_TOKEN not set; skipping login
> ```
> 
> Please also check that you're on the latest version and haven't edited the `Dockerfile`. It really shouldn't try to execute `/start.sh` - our file is named `docker-start.sh`.

(base) PS S:\SimpleTuner> docker buildx build -f Dockerfile --platform linux/amd64 --output type=docker --provenance false
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
(base) PS S:\SimpleTuner>

**Comment by komninoschatzipapas** [comment]
@protector131090 I recommend taking some time to familiarize yourself with how Docker works.
