### ISSUE TITLE
Log images as a normal log entry so you get a slider that lets you see past images

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [bghira/SimpleTuner#731]
I log them like this, which will give you a slider and let you see past images:

```py
            formatted_images = []

            for log in image_logs:
                images = log["images"]
                validation_prompt = log["prompt"]
                validation_image = log.get("validation_image", None)

                for image in images:
                    image = wandb.Image(image, caption=validation_prompt)
                    formatted_images.append(image)

            tracker.log({"validation": formatted_images})
```

**Comment by bghira** [comment]
but it doesn't handle multi-resolution or multi-image-per-prompt validations like the table mode does. maybe there's some wandb docs on how to get a table slider.

**Comment by AmericanPresidentJimmyCarter** [comment]
I think we can probably just automatically log as a list of images if the images are square, and if they aren't just log the way it currently does.

**Comment by AmericanPresidentJimmyCarter** [comment]
And yeah, step slider for table is an open issue: https://github.com/wandb/wandb/issues/6286

**Comment by bghira** [comment]
but you can change the res list and then the table shows up with a 2nd list.. i just want the table to work really

**Comment by bghira** [comment]
see https://github.com/bghira/SimpleTuner/pull/872
