### ISSUE TITLE
Some questions about train dataset config setting

### ISSUE THREAD

**Issue by LianShuaiLong** [bghira/SimpleTuner#733]
i need some help,
first, i  configure traindata setting according to the Recommended like the following
<img width="1629" alt="image" src="https://github.com/user-attachments/assets/d5f8bd92-3355-4740-888d-fc9e4271d71a">
<img width="628" alt="image" src="https://github.com/user-attachments/assets/37b898b1-6816-4921-ba2c-a729b12635e7">
but i get the error:
<img width="1639" alt="image" src="https://github.com/user-attachments/assets/22431bdf-3bb0-413d-b48e-53b97b80ed5f">
how can i fix this?

**Comment by bghira** [comment]
for a value of `1` which is megapixels, you need to use `resolution_type=area`

or to use `=pixel`, keep resolution values at 1024. not 1
