### ISSUE TITLE
Lora generated by Simpletuner not working on a1111 Forge

### ISSUE THREAD

**Issue by BenDes21** [bghira/SimpleTuner#734]
Hi there, got very good results from my trainings according to the validation images of Simpletuner but as soon as I try my lora's ( .safetensors ) on a1111 forge with the Flux fp8 version, it's seems to not working ( lora's are visible on lora's tab and I correctly call the trigger word and the <lora file>. Any solutions ? thanks!

**Comment by bghira** [comment]
I think the author of forge is actively developing that platform again, and you could provide them with a non-working LoRA.
