### ISSUE TITLE
Quick question regarding flux guidance real + no cfg until timestep

### ISSUE THREAD

**Issue by OliviaOliveiira** [bghira/SimpleTuner#735]
Hey once again!
I just want to make sure that I'm using these two correctly. (like without pointing out the basic guidance)

export VALIDATION_PROMPT="Mm0n, a woman, infected face"
export VALIDATION_GUIDANCE_REAL=0.6
export VALIDATION_NO_CFG_UNTIL_TIMESTEP=2
export VALIDATION_GUIDANCE_RESCALE=0.0
export VALIDATION_STEPS=200
export VALIDATION_NUM_INFERENCE_STEPS=20
export VALIDATION_NEGATIVE_PROMPT=""
export VALIDATION_SEED=42
export VALIDATION_RESOLUTION=$RESOLUTION

**Comment by bghira** [comment]
anything <= 1.0 disables the real cfg.

it's fine, it will work. but you won't get CFG in this without `--flux_guidance_value=` and maybe even use `--flux_guidance_min`/max to set a range with `range` mode

**Comment by OliviaOliveiira** [comment]
> anything <= 1.0 disables the real cfg.
> 
> it's fine, it will work. but you won't get CFG in this without `--flux_guidance_value=` and maybe even use `--flux_guidance_min`/max to set a range with `range` mode

Thanks!
