### ISSUE TITLE
Does anyone use FLUX lora really effectivly in A1111 or ComfyUI or Forge or Fooocus ?

### ISSUE THREAD

**Issue by NBSTpeterhill** [bghira/SimpleTuner#738]
Train is successfully.
But when use the LORA, here are no effect at all.
Dose anybody know how to solve the problem ?

**Comment by LianShuaiLong** [comment]
same problem

**Comment by LianShuaiLong** [comment]
> i tested my loras in comfy and forge and they works great.

have you update your comfyui to the newest version?

**Comment by quzopl** [comment]
> > i tested my loras in comfy and forge and they works great.
> 
> have you update your comfyui to the newest version?

yes , comfy version 2517[e9589d](2024-08-11) , but i suggest to remove all custom nodes and especially a fooocus  and leave only manager

**Comment by LianShuaiLong** [comment]
> > > i tested my loras in comfy and forge and they works great.
> > 
> > 
> > have you update your comfyui to the newest version?
> 
> yes , comfy version 2517[e9589d](2024-08-11) , but i suggest to remove all custom nodes and especially a fooocus and leave only manager

why?🤔️

**Comment by LianShuaiLong** [comment]
> > > i tested my loras in comfy and forge and they works great.
> > 
> > 
> > have you update your comfyui to the newest version?
> 
> yes , comfy version 2517[e9589d](2024-08-11) , but i suggest to remove all custom nodes and especially a fooocus and leave only manager

Can you help me configure my training data?
my train dataset like (image.png,image.txt) pairs in a folder,where image.txt are image caption, and image size is 1024x1024,
i want to train flux lora with 8gpus 1 machine
any suggest to configure training configs?

**Comment by bghira** [comment]
you guys should have these conversations in the Discussions tab or on Discord please
