### ISSUE TITLE
What is the processing logic for a training dataset of the textfile caption type?

### ISSUE THREAD

**Issue by LianShuaiLong** [bghira/SimpleTuner#740]
What does "filtered prompt" mean in the debug log? Does it mean that this prompt has been filtered out and will not participate in the training?
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/d7bc6f39-8429-4364-a7ae-2e787cf5d9bb">

**Comment by LianShuaiLong** [comment]
anyone can help?

**Comment by bghira** [comment]
it is after applying any regex filters. it is just a debug line

**Comment by bghira** [comment]
the regular expressions are useful if you find a pattern in your captions due to the use of eg. BLIP or CogVLM. BLIP outputs a string 'arafed' for no reason, and CogVLM loves 'the image showcases'. the regex can remove these. see filter_list.txt
