### ISSUE TITLE
stuck at poetry install --no-root, pending?[FLUX}

### ISSUE THREAD

**Issue by krigeta** [bghira/SimpleTuner#743]
I am using massedcompute cloud service and using Ubuntu and following the steps mentioned in the quickstart but when I run `poetry install --no-root` I get this output[below] that is pending for almost hours, so the credit expired and I need help to fix this

```
Installing dependencies from lock file

Package operations: 102 installs, 3 updates, 0 removals

  - Installing nvidia-nvjitlink-cu12 (12.4.99)
  - Installing markupsafe (2.1.5): Pending...
  - Installing mpmath (1.3.0): Pending...
  - Installing nvidia-cublas-cu12 (12.4.2.65): Pending...
  - Installing nvidia-cusparse-cu12 (12.3.0.142): Pending...
```

**Comment by bghira** [comment]
this is unfortunately a cloud provider issue. they will have to refund your credits, hopefully they have a good policy for that.

**Comment by krigeta** [comment]
> this is unfortunately a cloud provider issue. they will have to refund your credits, hopefully they have a good policy for that.

May you please provide cheap cloud providers that wont generate this issue?

**Comment by bghira** [comment]
the one recommended in the guide is TensorDock. I don't work there nor am I affiliated with them, but they have had good offerings in the past. Lambda Labs is probably the best option, but might not be as affordable - one might be cheaper for low end GPUs and the other, for higher end.

**Comment by krigeta** [comment]
> the one recommended in the guide is TensorDock. I don't work there nor am I affiliated with them, but they have had good offerings in the past. Lambda Labs is probably the best option, but might not be as affordable - one might be cheaper for low end GPUs and the other, for higher end.

so I am using tensordock Ubuntu 22.04 with 24GB RAM, RTX 8000 48GB Card, but it is CLI and I don't know how to use it, is there any way I can use a GUI to access the virtual desktop to access the VM?

**Comment by bghira** [comment]
i don't think desktop GUIs on containers is a standard feature, you will have to ask around for help with command line tools

**Comment by bghira** [comment]
seems like a system issue, not any problem with simpletuner

**Comment by ttio2tech** [comment]
the installing hangs on my machine. Can the project move away from poetry?

**Comment by bghira** [comment]
it's just the dependency management, you are not bound to using poetry. you can use `DISABLE_UPDATES=1` to disable the call to poetry at startup and just manage deps however you want.

but doing so makes it impossible for me to follow up on most issue reports and so they will not be actioned upon when this is the case.

poetry is simply how we manage dependencies across different platforms cleanly and if any issues arise, they are local to your system and debugging this is unfortunately out-of-scope for a diffusion training project.
