### ISSUE TITLE
Do not throw away images if your dataset is not divisible by batch size

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [bghira/SimpleTuner#745]
There has to be some reasonable way to do this.

**Comment by TheZennou** [comment]
I also encountered this issue, flux responds well to small datasets but high batches sizes disagrees with that. My solution was to force less buckets by making a quick and dirty python script to process the images into buckets more intelligently. Make sure there is only five. Would be great to have a fix right in the tuner though.
