### ISSUE TITLE
FLUX training lora has no effect?

### ISSUE THREAD

**Issue by LianShuaiLong** [bghira/SimpleTuner#750]
I have been troubled for several days. I used SimpleTurner to train Flux LoRA, but it had no effect. The training process went smoothly, and there were no errors when loading it with the latest version of ComfyUI. However, after adding the trigger words for LoRA, there was no change compared to Flux. Below is my complete project
[SimpleTuner_train.zip](https://github.com/user-attachments/files/16595351/SimpleTuner_train.zip)

i train flux lora with 8 gpus,

**Comment by bghira** [comment]
this is a common problem with comfyUI. not really sure what's wrong with it. you should open an issue over there.

**Comment by LianShuaiLong** [comment]
> this is a common problem with comfyUI. not really sure what's wrong with it. you should open an issue over there.

is there anything wrong in my training code or training setting?

**Comment by bghira** [comment]
nope, that looks fine - the defaults work. set `VALIDATION_STEPS=100` or something, you will see it changing.. yeah. a lot of people report this with comfyUI. no clue, i don't ever use it.

**Comment by LianShuaiLong** [comment]
> nope, that looks fine - the defaults work. set `VALIDATION_STEPS=100` or something, you will see it changing.. yeah. a lot of people report this with comfyUI. no clue, i don't ever use it.

thanks,

**Comment by markrmiller** [comment]
For me, I think the problem was actually setting it to train all the Lora layers. I went back to the default and it works again in comfy.

**Comment by LianShuaiLong** [comment]
> For me, I think the problem was actually setting it to train all the Lora layers. I went back to the default and it works again in comfy.

i trained lora layers with default setting, it works fine with diffusers but has no effect in comfyui 😓

**Comment by bghira** [comment]
**this is a comfyUI issue**. the weights being quantised before fusing results in practically no change to the base weights. the lora works in bf16 because the weights are scaled appropriately. he has to fix this... i wish @comfyanonymous would do something about this, as it's rather looking embarrassing

**Comment by bghira** [comment]
he could also just implement online lora inference but that seems like the design of the platform makes it impossible. i think he might be one of the only people who can unwrap the logic.

**Comment by bghira** [comment]
ok i managed to resolve this one by removing a workaround for the save/load issue with quanto. apparently even though it works to create the lora, it messes up the keys, and the resume bug will have to be solved some other way
