### ISSUE TITLE
AssertionError: only bfloat 16 is supported.

### ISSUE THREAD

**Issue by markrmiller** [bghira/SimpleTuner#755]
I've been training fine and then I switched on gradient checkpointing. Since then, regardless of what settings I try around precision and datatypes, I get this every time:

```
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2420, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 1945, in main
    optimizer.step()
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 170, in step
    self.optimizer.step(closure)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 130, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 484, in wrapper
    out = func(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SimpleTuner/helpers/training/adam_bfloat16/__init__.py", line 67, in step
    assert p.dtype == torch.bfloat16, "only bfloat 16 is supported."
AssertionError: only bfloat 16 is supported.
```
`+ accelerate launch --mixed_precision=bf16 --num_processes=1 --num_machines=1 --dynamo_backend=no train.py --model_type=lora --pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev --gradient_checkpointing --set_grads_to_none --gradient_accumulation_steps=1 --resume_from_checkpoint=latest --snr_gamma=5 --data_backend_config=config/multidatabackend.json --num_train_epochs=0 --max_train_steps=8000 --metadata_update_interval=65 --adam_bfloat16 --learning_rate=1e-4 --lr_scheduler=constant --seed 42 --lr_warmup_steps=50 --output_dir=/workspace/output/models --inference_scheduler_timestep_spacing=trailing --training_scheduler_timestep_spacing=trailing --mixed_precision=bf16 --lora_rank=64 --lora_alpha=64 --max_grad_norm=1.0 --base_model_precision=int8-quanto --flux --flux_guidance_value=1.0 --flux_lora_target=mmdit --train_batch=1 --max_workers=32 --read_batch_size=25 --write_batch_size=64 --caption_dropout_probability=0.05 --torch_num_threads=8 --image_processing_batch_size=32 --vae_batch_size=4 '--validation_prompt=aqzt in a full body photo, masterpiece, best quality, ultra-detailed, disheveled hair, detailed eyes, moist skin, intricate details' --num_validation_images=1 --validation_num_inference_steps=20 --validation_seed=42 --minimum_image_size=1024 --resolution=1024 --validation_resolution=1024x1024 --resolution_type=pixel --checkpointing_steps=100 --checkpoints_total_limit=3 --validation_steps=100 --tracker_run_name=simpletuner-flux --tracker_project_name=flux-training --validation_guidance=3.5 --validation_guidance_real=1.0 --validation_guidance_rescale=0.0 --validation_negative_prompt=`

I've tried everything I can find to try, it doesn't matter, it just spits out that assertion error. base_model_default_dtype hasn't helped, gradient_precision hasn't helped, trying whatever combo I can of the other precision and datatype options has not helped.

I've also tried different values for:
```
export MIXED_PRECISION="bf16"
export PURE_BF16=true
```

**Comment by markrmiller** [comment]
This is happening whether I use gradient checkpointing or not, so it must have just been picking up the latest repo, not that change.

**Comment by bghira** [comment]
please set SIMPLETUNER_LOG_LEVEL=DEBUG and attach debug.log

**Comment by xjabrvccp** [comment]
Having the same error, anyone fixed it?

**Comment by bghira** [comment]
see above comment about debug.log

**Comment by drewbaumann** [comment]
[debug.log](https://github.com/user-attachments/files/16620410/debug.log)
@bghira Here is mine

**Comment by bghira** [comment]
ok the thing is gradient_precision=fp32 is incomptible with adamw_bf16 training - it also needs a lotta vram and not a good idea for smaller systems. but it would work with probably adafactor and fp32 weights on a larger system if you wanted.

i would recommend removing --gradient_precision=fp32 from a config and reducing gradient_accumulation_steps to 1

**Comment by bghira** [comment]
so there is a workaround and i can commit a fix soon but it is tied up in some other changes at the moment

**Comment by bghira** [comment]
this is fixed

**Comment by drewbaumann** [comment]
Thanks @bghira !

**Comment by bghira** [comment]
ironically it fixed the comfyui issue to solve this one.

**Comment by xjabrvccp** [comment]
@bghira Thanks big boss
