### ISSUE TITLE
CLIP Input Truncation Due to Token Limit in Processing

### ISSUE THREAD

**Issue by magicwang1111** [bghira/SimpleTuner#760]
I've noticed that when processing inputs using the CLIP model, the input text is often truncated because the model can only handle sequences up to 77 tokens. This truncation results in incomplete analysis, especially when dealing with longer descriptive texts or complex visual scenes.

Example:
Here is an example log output showing the issue:

31/9570 [00:18:14:30, 1.76it/s]The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: '[group of elderly ladies is seated on a bench, one is knitting while the others are engaged in a conversation. the background shows various shop'
Issue:
In this case, the input sequence describing a group of elderly ladies and the background scene was cut off. As a result, any context or details beyond the 77-token limit are lost, which can impact the quality and accuracy of the analysis or generation tasks relying on this input.

**Comment by magicwang1111** [comment]
![image](https://github.com/user-attachments/assets/a6c76950-5f3a-4a37-b8ba-f7f00c15e652)
how to solve it?

**Comment by bghira** [comment]
you cannot change clip seq len
