### ISSUE TITLE
Need some help 

### ISSUE THREAD

**Issue by NuaghtySociety** [bghira/SimpleTuner#761]
train.py: error: unrecognized arguments: flux}
Traceback (most recent call last):
  File "/workspace/SimpleTuner/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/SimpleTuner/.venv/bin/python', 'train.py', '--model_type=lora', '--pretrained_model_name_or_path=black-forest-labs/FLUX.1-dev', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=1', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=config/multidatabackend.json', '--num_train_epochs=0', '--max_train_steps=3000', '--metadata_update_interval=65', '--use_prodigy_optimizer', '--learning_rate=1', '--lr_scheduler=sine', '--seed', '42', '--lr_warmup_steps=1000', '--output_dir=output/models', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--base_model_precision=int8-quanto', '--flux', '--push_to_hub', '--hub_model_id={hermes', 'flux}', '--push_checkpoints_to_hub', '--train_batch=1', '--max_workers=32', '--read_batch_size=25', '--write_batch_size=64', '--caption_dropout_probability=0.1', '--torch_num_threads=8', '--image_processing_batch_size=32', '--vae_batch_size=4', '--validation_prompt=ethnographic photography of a xwe hermes handbag, a women posing in the street holding xwe hermes handbag  ', '--num_validation_images=1', '--validation_num_inference_steps=30', '--validation_seed=42', '--minimum_image_size=1024', '--resolution=1024', '--validation_resolution=1024', '--resolution_type=pixel', '--checkpointing_steps=100', '--checkpoints_total_limit=3', '--validation_steps=8000', '--tracker_run_name=simpletuner-v1', '--tracker_project_name={hermes flux}', '--validation_guidance=3.5', '--validation_guidance_real=1.0', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=blurry, cropped, ugly']' returned non-zero exit status 2.

**Comment by bghira** [comment]
unrecognised argument --flux. your install might be corrupted?
