### ISSUE TITLE
Error on FLUX.1 training

### ISSUE THREAD

**Issue by shencuifeng** [bghira/SimpleTuner#780]
In the FLUX.1 training, when I set batch size greater than 1, and set **args.flux_fast_schedule** to true, it has this error on line 1479:
`RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 3`
Is this because missing `sigmas = sigmas.view(-1, 1, 1, 1)` on line 1473?

**Comment by bghira** [comment]
are you training Schnell? this feature hasn't really been updated since the Flux changes started rolling in.
