### ISSUE TITLE
No module named 'optimi',You must initialize the accelerate state by calling either `PartialState()` or `Accelerator()` before using the logging utility.

### ISSUE THREAD

**Issue by magicwang1111** [bghira/SimpleTuner#809]
(flux) [wangxi@v100-4 SimpleTuner]$ CUDA_VISIBLE_DEVICES=2 sh train.sh
find: ‘/mnt/data1/wangxi/SimpleTuner/.venv’: No such file or directory
/lib
VALIDATION_NEGATIVE_PROMPT not set, defaulting to empty.
Traceback (most recent call last):
  File "/mnt/data1/wangxi/SimpleTuner/helpers/training/optimizer_param.py", line 20, in <module>
    import optimi
ModuleNotFoundError: No module named 'optimi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data1/wangxi/SimpleTuner/train.py", line 30, in <module>
    from helpers.arguments import parse_args
  File "/mnt/data1/wangxi/SimpleTuner/helpers/arguments.py", line 10, in <module>
    from helpers.training.optimizer_param import (
  File "/mnt/data1/wangxi/SimpleTuner/helpers/training/optimizer_param.py", line 24, in <module>
    logger.error(
  File "/home/wangxi/miniconda3/envs/flux/lib/python3.10/logging/__init__.py", line 1858, in error
    self.log(ERROR, msg, *args, **kwargs)
  File "/home/wangxi/miniconda3/envs/flux/lib/python3.10/site-packages/accelerate/logging.py", line 52, in log
    raise RuntimeError(
RuntimeError: You must initialize the accelerate state by calling either `PartialState()` or `Accelerator()` before using the logging utility.
Traceback (most recent call last):
  File "/home/wangxi/miniconda3/envs/flux/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/wangxi/miniconda3/envs/flux/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/wangxi/miniconda3/envs/flux/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/wangxi/miniconda3/envs/flux/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wangxi/miniconda3/envs/flux/bin/python', 'train.py', '--model_type=lora', '--pretrained_model_name_or_path=/mnt/data1/shared_data/FLUX.1-dev/', '--gradient_checkpointing', '--set_grads_to_none', '--gradient_accumulation_steps=1', '--resume_from_checkpoint=latest', '--snr_gamma=5', '--data_backend_config=config/multidatabackend.json', '--num_train_epochs=0', '--max_train_steps=3000', '--metadata_update_interval=65', '--optimizer=adamw_bf16', '--learning_rate=3e-4', '--lr_scheduler=constant_with_warmup', '--seed', '42', '--lr_warmup_steps=300', '--output_dir=output/models/0819flux-Your-name-lora128', '--inference_scheduler_timestep_spacing=trailing', '--training_scheduler_timestep_spacing=trailing', '--report_to=wandb', '--allow_tf32', '--mixed_precision=bf16', '--lora_rank=128', '--validation_torch_compile=false', '--lora_init_type=default', '--base_model_precision=fp8-quanto', '--offset_noise', '--noise_offset=0.02', '--flux', '--flux_guidance_value=1.0', '--flux_lora_target=all+ffs', '--push_to_hub', '--hub_model_id=0819flux-Your-name-lora128lora-training', '--push_checkpoints_to_hub', '--train_batch=2', '--max_workers=32', '--read_batch_size=25', '--write_batch_size=64', '--caption_dropout_probability=0.1', '--torch_num_threads=8', '--image_processing_batch_size=32', '--vae_batch_size=4', "--validation_prompt=qxxy style,Your_name,best quality,This is a high-resolution anime still featuring a young male character with black hair wearing a white school uniform with a green and yellow tie. He appears startled or surprised, with his mouth slightly open and a hand to his cheek, as though he has just witnessed something unexpected. The setting seems to be a cafe with a modern, airy interior, as indicated by the wooden trusses on the ceiling and hanging industrial-style lamps. The daylight filters through the windows, creating a bright atmosphere. No other characters are visible, which places the entire focus on the young man's reaction.,1boy, necktie, male_focus, solo, school_uniform, indoors, striped_necktie, green_necktie, short_sleeves, shirt, upper_body", '--num_validation_images=1', '--validation_num_inference_steps=20', '--validation_seed=42', '--minimum_image_size=1024', '--resolution=1024', '--validation_resolution=1024', '--resolution_type=pixel', '--checkpointing_steps=300', '--checkpoints_total_limit=10', '--validation_steps=100', '--tracker_run_name=simpletuner-flux', '--tracker_project_name=0819flux-Your-name-lora128lora-training', '--validation_guidance=3.5', '--validation_guidance_real=1.0', '--validation_guidance_rescale=0.0', '--validation_negative_prompt=']' returned non-zero exit status 1.
(flux) [wangxi@v100-4 SimpleTuner]$ pip install optimi
ERROR: Could not find a version that satisfies the requirement optimi (from versions: none)
ERROR: No matching distribution found for optimi
(flux) [wangxi@v100-4 SimpleTuner]$

**Comment by vikm2o** [comment]
@magicwang1111 what was the resolution ? I am facing the same issue

**Comment by nguyendothanhtruc** [comment]
For installing the required package, use cmd:
> pip install torch-optimi
