### ISSUE TITLE
Exception: No images were discovered by the bucket manager in the dataset: xxxx.

### ISSUE THREAD

**Issue by michaelcyshield** [bghira/SimpleTuner#836]
I get this error 
`------------------------------
2024-08-21 21:15:08,041 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: xxxx., traceback: Traceback (most recent call last):
  File "SimpleTuner/train.py", line 588, in main
    configure_multi_databackend(
  File "/home/administrator/michael/SimpleTuner/helpers/data_backend/factory.py", line 810, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: xxxx.
`
when I decrease my dataset size, however, according the constraints of  the readme I should be fine, I have batch size 1 and grad accumulation 1 and VAE batch size  exported in config.env to be equal to 4.
here is my multidatabackend.json, my dataset consists of jpg images that are of bigger than 512 x 512 in both widget and height and unbounded maximum size

`[
    {
      "id": "xxx",
      "type": "local",
      "crop": true,
      "crop_aspect": "square",
      "crop_style": "center",
      "resolution": 512,
      "minimum_image_size": 512,
      "maximum_image_size": 768,
      "target_downsample_size": 512,
      "resolution_type": "pixel",
      "cache_dir_vae": "cache/vae/flux/xxx",
      "instance_data_dir": "datasets/xxxx/",
      "disabled": false,
      "skip_file_discovery": "",
      "caption_strategy": "parquet",
      "parquet": {
    "path": "datasets/xxxx/captions.parquet",
    "filename_column": "filename",
    "caption_column": "caption",
    "identifier_includes_extension": true
    
  },
      "metadata_backend": "parquet",
      "preserve_data_backend_cache": false,
      "repeats":2
    },
    {
      "id": "text-embeds",
      "type": "local",
      "dataset_type": "text_embeds",
      "default": true,
      "cache_dir": "cache/text/flux/partial_presidential_pics_high_res",
      "disabled": false,
      "write_batch_size": 128
    }
  ]`

this is my config.env
'RESUME_CHECKPOINT='latest'
DATALOADER_CONFIG='config/multidatabackend.json'
ASPECT_BUCKET_ROUNDING='2'
TRAINING_SEED='42'
USE_EMA='false'
USE_XFORMERS='false'
MINIMUM_RESOLUTION='0'
OUTPUT_DIR='output/models'
USE_DORA='false'
USE_BITFIT='false'
PUSH_TO_HUB='false'
PUSH_CHECKPOINTS='false'
NUM_EPOCHS='200'
MAX_NUM_STEPS='0'
CHECKPOINTING_STEPS='1000'
CHECKPOINTING_LIMIT='3'
HUB_MODEL_NAME='simpletuner-lora'
DEBUG_EXTRA_ARGS=''
MODEL_TYPE='lora'
MODEL_NAME='black-forest-labs/FLUX.1-dev'
FLUX='true'
KOLORS='false'
STABLE_DIFFUSION_3='false'
STABLE_DIFFUSION_LEGACY='false'
FLUX_LORA_TARGET='all'
TRAIN_BATCH_SIZE='1'
USE_GRADIENT_CHECKPOINTING='true'
GRADIENT_ACCUMULATION_STEPS='1'
CAPTION_DROPOUT_PROBABILITY='0.1'
RESOLUTION_TYPE='pixel_area'
RESOLUTION='512'
VALIDATION_SEED='42'
VALIDATION_STEPS='1000'
VALIDATION_RESOLUTION='1024x1024'
VALIDATION_GUIDANCE='4'
VALIDATION_GUIDANCE_RESCALE='0.0'
VALIDATION_NUM_INFERENCE_STEPS='20'
VALIDATION_PROMPT='A photo of President of Egypt Abdel Fattah EL sisi giving a speech'
ALLOW_TF32='false'
MIXED_PRECISION='bf16'
OPTIMIZER='adamw_bf16'
LEARNING_RATE='4e-4'
LR_SCHEDULE='polynomial'
LR_WARMUP_STEPS='0'
ACCELERATE_EXTRA_ARGS=''
TRAINING_NUM_PROCESSES='1'
TRAINING_NUM_MACHINES='1'
VALIDATION_TORCH_COMPILE='false'
TRAINER_DYNAMO_BACKEND='no'
TRAINER_EXTRA_ARGS='--lora_rank=64 --lr_end=1e-8 --base_model_precision=int8-quanto --compress_disk_cache'
export SIMPLETUNER_LOG_LEVEL=INFO
export SIMPLETUNER_TRAINING_LOOP_LOG_LEVEL=INFO
export VAE_BATCH_SIZE=4
'

**Comment by bghira** [comment]
you need an absolute path for your data directory with the parquet backend

**Comment by bghira** [comment]
otherwise just bump log level to DEBUG and re-run and check debug.log

**Comment by michaelcyshield** [comment]
doesn't seem to fix the issue, but here is the debug.log. if you can help me figure out the issue. it seems to be finding the file
[debug.log](https://github.com/user-attachments/files/16697830/debug.log)

**Comment by bghira** [comment]
```
2024-08-21 22:25:10,894 [DEBUG] (ParquetMetadataBackend) Reading image /home/administrator/michael/SimpleTuner/datasets/partial_presidential_pics_high_res/train/Prime Minister of Japan Fumio Kishida_49.jpg metadata from parquet backend column filename without instance root dir prefix /home/administrator/michael/SimpleTuner/datasets/partial_presidential_pics_high_res: train/Prime Minister of Japan Fumio Kishida_49.jpg.
```

well, does the filename column contain the `train/` prefix?

**Comment by michaelcyshield** [comment]
> ```
> 2024-08-21 22:25:10,894 [DEBUG] (ParquetMetadataBackend) Reading image /home/administrator/michael/SimpleTuner/datasets/partial_presidential_pics_high_res/train/Prime Minister of Japan Fumio Kishida_49.jpg metadata from parquet backend column filename without instance root dir prefix /home/administrator/michael/SimpleTuner/datasets/partial_presidential_pics_high_res: train/Prime Minister of Japan Fumio Kishida_49.jpg.
> ```
> 
> well, does the filename column contain the `train/` prefix?

it didn't but I just edited the parquet file so all rows start with train/ now and it didn't work, I also tried to add train/ to the data instance dir and no luck there. Should I be making metadata json files for images and then adding them to the parquet dataset using the toolkit or is that not necessary?

**Comment by michaelcyshield** [comment]
Oddly, adding width and height columns did not resolve this error. in the logs it prints out the widths and heights correctly but still throws the same error. Could there be something else missing that the exception is not mentioning?
[debug.log](https://github.com/user-attachments/files/16706780/debug.log)

**Comment by michaelcyshield** [comment]
ahh, After looking at the code I realised you need to define what column is the width and height column in the multidatabackend.json. All is good now!

**Comment by bghira** [comment]
hmm it should use width and height by default

**Comment by bghira** [comment]
did you see any kinda error like this? it occurs during bucket caching. maybe it's too late to find out... now that i think about it... yeah... it probably is

```py
            width_column = self.parquet_config.get("width_column")
            height_column = self.parquet_config.get("height_column")
            if width_column is None or height_column is None:
                raise ValueError(
                    "ParquetMetadataBackend requires width and height columns to be defined."
                )
```

**Comment by michaelcyshield** [comment]
> did you see any kinda error like this? it occurs during bucket caching. maybe it's too late to find out... now that i think about it... yeah... it probably is
> 
> ```python
>             width_column = self.parquet_config.get("width_column")
>             height_column = self.parquet_config.get("height_column")
>             if width_column is None or height_column is None:
>                 raise ValueError(
>                     "ParquetMetadataBackend requires width and height columns to be defined."
>                 )
> ```

Yes, I did see, but I was just a bit confused because I had these columns in my parquet, but it turns out I needed to define it in the databacket.json, So I was confused for a while because I thought if I named the columns just like in the exception above, then I'd be a okay, but yea I needed to explicitly supply these columns to the backend. Maybe if I were to nitpick, either allow the backend to search for a 'width' and 'height' column by default if it is not overridden in the backend, or  add this to that error message above,
"ParquetMetadataBackend requires width and height columns to be defined. Make sure they exist in your parquet file, and are defined in the multidatabackend.json"  an example in the readme could also go a long way, but I am not quite sure how the code in the readmes work if they do not have width and height columns in their multidatabackend.json
