### ISSUE TITLE
2024-08-22 11:26:07|[LyCORIS]-INFO: create LyCORIS: 0 modules.

### ISSUE THREAD

**Issue by magicwang1111** [bghira/SimpleTuner#844]
2024-08-22 11:26:07|[LyCORIS]-INFO: create LyCORIS: 0 modules.
2024-08-22 11:26:07|[LyCORIS]-INFO: module type table: {}

bad lycoris config

_Originally posted by @bghira in https://github.com/bghira/SimpleTuner/issues/843#issuecomment-2303640730_
            

{
"algo": "lokr",
"multiplier": 1.0,
"linear_dim": 1000000,
"linear_alpha": 1,
"factor": 16
}

i use your example lycoris config

export TRAINER_EXTRA_ARGS+=" --lora_type=lycoris --lycoris_config=config/lycoris_config.json"

**Comment by bghira** [comment]
well the default is just an exmple of where it goes not necessarily the setting to use. cc @AmericanPresidentJimmyCarter
