### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x16 and 64x3072)

### ISSUE THREAD

**Issue by xlbryantx** [bghira/SimpleTuner#847]
File "/db-mnt/mnt/efs-mount/home/ryanxzhang/project/SimpleTuner/.venv/lib/python3.11/site-packages/optimum/quanto/tensor/qtensor_func.py", line 126, in forward
    output = torch.ops.quanto.qbytes_mm(input, other._data, other._scale)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/db-mnt/mnt/efs-mount/home/ryanxzhang/project/SimpleTuner/.venv/lib/python3.11/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/db-mnt/mnt/efs-mount/home/ryanxzhang/project/SimpleTuner/.venv/lib/python3.11/site-packages/optimum/quanto/library/qbytes_mm.py", line 88, in qbytes_mm_impl_cuda
    return qbytes_mm(activations, weights, output_scales)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/db-mnt/mnt/efs-mount/home/ryanxzhang/project/SimpleTuner/.venv/lib/python3.11/site-packages/optimum/quanto/library/qbytes_mm.py", line 33, in qbytes_mm
    return torch.matmul(activations, weights.t())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x16 and 64x3072)

**Comment by bghira** [comment]
looks like you're using the wrong VAE somehow.

**Comment by bghira** [comment]
can you share your config and debug.log ? it seems like something is allowing you to proceed in a way that it should not be.

**Comment by xlbryantx** [comment]
> can you share your config and debug.log ? it seems like something is allowing you to proceed in a way that it should not be.

export OUTPUT_DIR="/db-mnt/mnt/efs-mount/home/ryanxzhang/saved_models/flux_lora"
RESUME_CHECKPOINT='latest'
DATALOADER_CONFIG='config/multidatabackend.json'
ASPECT_BUCKET_ROUNDING='2'
TRAINING_SEED='42'
USE_EMA='false'
USE_XFORMERS='false'
MINIMUM_RESOLUTION='0'
OUTPUT_DIR='./config/config.env_flux'
USE_DORA='false'
USE_BITFIT='false'
LORA_TYPE='lycoris'
LYCORIS_CONFIG='config/lycoris_config.json'
PUSH_TO_HUB='false'
PUSH_CHECKPOINTS='false'
MAX_NUM_STEPS='3000'
NUM_EPOCHS='0'
CHECKPOINTING_STEPS='250'
CHECKPOINTING_LIMIT='5'
HUB_MODEL_NAME='simpletuner-lora'
DEBUG_EXTRA_ARGS=''
MODEL_TYPE='lora'
MODEL_NAME='black-forest-labs/FLUX.1-dev'
FLUX='true'
KOLORS='false'
STABLE_DIFFUSION_3='false'
STABLE_DIFFUSION_LEGACY='false'
TRAIN_BATCH_SIZE='1'
USE_GRADIENT_CHECKPOINTING='true'
GRADIENT_ACCUMULATION_STEPS='1'
CAPTION_DROPOUT_PROBABILITY='0.1'
RESOLUTION_TYPE='pixel_area'
RESOLUTION='1024'
VALIDATION_SEED='42'
VALIDATION_STEPS='250'
VALIDATION_RESOLUTION='1024x1024'
VALIDATION_GUIDANCE='3.0'
VALIDATION_GUIDANCE_RESCALE='0.0'
VALIDATION_NUM_INFERENCE_STEPS='20'
VALIDATION_PROMPT='A photo-realistic image of a cat'
ALLOW_TF32='false'
MIXED_PRECISION='bf16'
OPTIMIZER='adamw_bf16'
LEARNING_RATE='1e-4'
LR_SCHEDULE='polynomial'
LR_WARMUP_STEPS='30'
BASE_MODEL_PRECISION='fp8-quanto'
ACCELERATE_EXTRA_ARGS=''
TRAINING_NUM_PROCESSES='1'
TRAINING_NUM_MACHINES='1'
VALIDATION_TORCH_COMPILE='false'
TRAINER_DYNAMO_BACKEND='no'
TRAINER_EXTRA_ARGS='--lr_end=1e-8 --compress_disk_cache'

**Comment by xlbryantx** [comment]
Sorry, I made a mistaken, I read the text_emb from sdxl folder when training flux lora.

**Comment by bghira** [comment]
the text embeds have the model_type at the end. this is strange. how did it make SDXL embeds with a flux suffix?

**Comment by piotr-sikora-v** [comment]
for me, it's just remove cache directory :)
