### ISSUE TITLE
the guid has many result(pseudo-camera-10k)

### ISSUE THREAD

**Issue by al-swaiti** [bghira/SimpleTuner#849]
i followed your guid to test flux lora , i have these result   i tried to use savetensors file as lora but theres no effect 
![image](https://github.com/user-attachments/assets/8f8651c4-00ba-48b8-a33f-07edb0593e18)

**Comment by bghira** [comment]
![image](https://github.com/user-attachments/assets/a4e2a4d1-09f7-49ca-b1a1-805098a5defc)

**Comment by al-swaiti** [comment]
thanks again  , i was mistaken , i train it on sdxl
