### ISSUE TITLE
If the VAE runs out of memory while caching, training continues onward but then crashes when it can't find the missing cache file

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [bghira/SimpleTuner#859]
Exception: (id=default_dataset_896) Some images were not correctly cached during the VAE Cache operations. Ensure --skip_file_discovery=vae is not set.
Problematic images: ['/root/SimpleTuner/dataset/36.png']

**Comment by pashanitw** [comment]
i am also getting the same issue. how to resolve it?

**Comment by mhirki** [comment]
Setting `VAE_BATCH_SIZE=1` should keep VRAM usage at a minimum when caching the latents.

**Comment by bghira** [comment]
i don't really have a low vram system on hand to test and not wanting to spin one up. but i've pushed a change for the thread to exit based on the error.

**Comment by pashanitw** [comment]
![Screenshot from 2024-08-25 17-18-52](https://github.com/user-attachments/assets/407cbb92-515c-412c-9c3e-fb28c8165036)
@bghira after pulling the latest changes from main i can confirm the training is working in my rtx 3090 24gb. once the training is done i will post the results as well !. thanks !

**Comment by Devil-Ideal** [comment]
> ![2024-08-25 17-18-52 的截图](https://private-user-images.githubusercontent.com/1389446/361228993-407cbb92-515c-412c-9c3e-fb28c8165036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MDQ3NTksIm5iZiI6MTczNjUwNDQ1OSwicGF0aCI6Ii8xMzg5NDQ2LzM2MTIyODk5My00MDdjYmI5Mi01MTVjLTQxMmMtOWMzZS1mYjI4YzgxNjUwMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMTAyMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFiYWY4NGRhMmY0NWIwNWJhODBiY2UyNjY4ODc5YmI4NzhlZjNjMzQwZDQ2ZWRiMmRiNWQyNGRkMmM1NWRkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qRfPmvs8KLE3TGFanDXvRwB0KWXO9jRs6I_Bu9tYJao) @bghira从主服务器中提取最新更改后，我可以确认训练在我的 rtx 3090 24gb 中进行。训练完成后，我也会发布结果！谢谢！

Hi ! Have you release your training results? Do you know if the vae_batch_size influence the lora tuning speed?
