### ISSUE TITLE
Need help with the training process

### ISSUE THREAD

**Issue by rohanNkhaire** [bghira/SimpleTuner#860]
I get the pytorch_model_weights.safetensor in the output folder. Then the process exits. Could you help me understand if the training is complete?

![Screenshot from 2024-08-24 09-15-40](https://github.com/user-attachments/assets/bdd5b387-69a9-4419-9fb3-5eacb386dafa)

**Comment by bghira** [comment]
you probably have one dataset and it has ignore_epochs=True
