### ISSUE TITLE
missing save code for Flux full finetune

### ISSUE THREAD

**Issue by Jack000** [bghira/SimpleTuner#864]
https://github.com/bghira/SimpleTuner/blob/66f9902ee7ca8abed3d57bfd162e1cbfa2d4aee6/train.py#L2351

am I crazy or is there no pipeline here for Flux full? It goes SD3, legacy, smoldit, and SDXL in the else.

might be related to https://github.com/bghira/SimpleTuner/issues/852

**Comment by bghira** [comment]
it's like an easter egg for someone who manages to do the full finetune on Flux. would you care to add it via PR?

**Comment by Jack000** [comment]
nah it's alright, should be a simple fix
