### ISSUE TITLE
Empty all_caption_files.json with textfile caption strategy

### ISSUE THREAD

**Issue by rengotj** [bghira/SimpleTuner#885]
Good morning,

I am training the model on a custom dataset with text file caption strategy.

The logs show an initialisation :
" 2024-07-31 15:16:51,255 [INFO] (DataBackendFactory) (id=SubDB_SD21) Initialise text embed pre-computation using the textfile caption strategy. We have 1980 captions to process."

But, the automatically created all_caption_files.json always remains empty. So, I am not sure that the labels are taken into account.
Do you have an explanation ?

Thank you so much.
Best regards.

**Comment by bghira** [comment]
is not really created anymore. that is some old code

**Comment by rengotj** [comment]
Thank you for your answer.
