### ISSUE TITLE
SDXL Loras do not load in ComfyUI, A1111

### ISSUE THREAD

**Issue by PsychoLogicAu** [bghira/SimpleTuner#898]
I have been attempting to train a couple of SDXL Loras to get familiar with SimpleTuner, but I cannot get them to load in either ComfyUI or A1111. The validation images output during training process are fine, so I am confident that the training process is working.

A1111 gives no error or warning message, but there is no effect.
ComfyUI complains when attempting to load (see attached)

[comfyui_error_log.txt](https://github.com/user-attachments/files/16789101/comfyui_error_log.txt)

**Comment by bghira** [comment]
if these are PEFT LoRAs, the issue is in how comfy loads the Diffusers LoRAs.

if it's LyCORIS, then there is a a deficiency in how Comfy handles that.

it's a state dict issue and these are up to the inference platform to handle, SDXL LoRAs haven't been modified in a long time.

**Comment by PsychoLogicAu** [comment]
As noted, they also do not work in A1111, I haven't yet tried Forge. I did test all the way back to release v0.9.7.8 to verify nothing from the Flux merges changed things, behavior is the same.

So to clarify your response there, both of the inference platforms are wrong?

**Comment by bghira** [comment]
if both of them are failing to load the keys but PEFT itself is able to save and load its own LoRAs then i guess it would stand to reason that both A111 and Comfy have an issue with loading things.

A1111 is notoriously bad about it. chances are you'll have to find a Diffusers LoRA converter script for those platforms.

**Comment by bghira** [comment]
alternatively you can go with LyCORIS LoKr and it will work pretty much everywhere that LyCORIS works, as it's using the one upstream library that most platforms are using - but not many of the UIs other than SD.Next use PEFT.

**Comment by PsychoLogicAu** [comment]
Thanks, I'll give that a try today

**Comment by bghira** [comment]
there's a couple conversion scripts in this repo already for SDXL stuff but i'm not sure if any of it is useful or for LoRAs. but if you do find a script that is useful and isn't in here, you could put it in via pull request.
