### ISSUE TITLE
Multi-gpu training does not work

### ISSUE THREAD

**Issue by yoshibenjo** [bghira/SimpleTuner#90]
I'm trying to train SDXL on 3x 80GB A100s. I'd precomputed the cache embeddings / vae latents when I was using a 1x A100 (I'm using networked storage that comes with Runpod, just flagging if this may be the issue). 

When trying to train with 3x, I've updated the `num_processes` param to `3` and passes the `--multi_gpu` param to accelerate. However, after 1/2 steps, I see the following error:

```
BUG] Starting into epoch 0 out of 0, final epoch will be 10
Steps:   0%| | 1/4710 [01:31<119:44:57, 91.55s/it, lr=8e-7, s2023-09-05 20:21:11,259 [INFO] Reducer buckets have been rebuilt in this iteration.
2023-09-05 20:21:11,438 [INFO] Reducer buckets have been rebuilt in this iteration.
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 1389, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 905, in main
    for step, batch in enumerate(train_dataloader):
  File "/root/.cache/pypoetry/virtualenvs/simpletuner-sqHYXouY-py3.10/lib/python3.10/site-packages/accelerate/data_loader.py", line 394, in __iter__
    next_batch = next(dataloader_iter)
  File "/root/.cache/pypoetry/virtualenvs/simpletuner-sqHYXouY-py3.10/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/.cache/pypoetry/virtualenvs/simpletuner-sqHYXouY-py3.10/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/.cache/pypoetry/virtualenvs/simpletuner-sqHYXouY-py3.10/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/workspace/SimpleTuner/train_sdxl.py", line 607, in <lambda>
    collate_fn=lambda examples: collate_fn(examples),
  File "/workspace/SimpleTuner/train_sdxl.py", line 557, in collate_fn
    ) = embed_cache.compute_embeddings_for_prompts(captions)
  File "/workspace/SimpleTuner/helpers/caching/sdxl_embeds.py", line 122, in compute_embeddings_for_prompts
    prompt_embeds_all = torch.cat(prompt_embeds_all, dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

Am I doing something wrong here?

**Comment by bghira** [comment]
that's likely because the SDXL part is broken / not fully implemented yet. the RC that's published should have working SD 2.x multi-GPU training. but the SDXL part had more optimizations that can be implemented, and it is taking longer to get it working.

**Comment by yoshibenjo** [comment]
@bghira Gotcha. Do you have a list of things that need to be implemented to get it working? I can help.

**Comment by bghira** [comment]
Currently, the work is aiming to distribute the VAE latent caching process among all subprocesses, but, it has made the process hang - at least it does on my setup, using the `main` branch.

**Comment by yoshibenjo** [comment]
After doing some more debugging, the embeds are being loaded from the cache and most are loaded into `cuda:0` but occasionally, almost randomly, an embed is loaded into `cuda:1` and this causes the above error.

**Comment by bghira** [comment]
are you using the main branch?

**Comment by yoshibenjo** [comment]
@bghira yes, main as of yesterday night.

**Comment by yoshibenjo** [comment]
could this have something to do with the fact that i ran the latent / embed caching logic on a different machine?

**Comment by bghira** [comment]
it wouldn't, the files are just retrieved by name, they don't contain eg. metadata

**Comment by bghira** [comment]
are you using NUM_PROCESSES=2 ?

**Comment by yoshibenjo** [comment]
@bghira apologies, i'm on the `release` branch. i followed the `INSTALL.md` page. commit `a0714dbe238fd8db3ab09c8d44b46f38b8d70b16`. 

i (hackily) fixed it by adding a check before `torch.cat` to make sure all tensors in `prompt_embeds_all` and `add_text_embeds_all` are on `cuda:0` and it seems to be training.

**Comment by bghira** [comment]
hm, that branch has zero multi-GPU support. it likely is oversampling images and using identical subsets across the devices.

**Comment by yoshibenjo** [comment]
@bghira I switched over to `main`. Things all seem to work fine with 0 changes. The training time is drastically slower than on main but I believe for the reasons you mention above. Looks like it leveraged the cache so I didn't hit the bug you've been hitting.

**Comment by bghira** [comment]
i'm actually starting to suspect some of the Vast instances i test on are old kernel.

**Comment by yoshibenjo** [comment]
@bghira grab a runpod if you can, they're always on the latest drivers / kernels. makes it easier to dev ml stuff imo

**Comment by yoshibenjo** [comment]
@bghira do you have any tips on speeding up training btw? i have a 155k image dataset, 768x768, 4x 80GB A100s and it looks like it's going to take 504 hours for 84k steps (10 epochs). Batch size is 5, grad accumulation is turned off.

**Comment by bghira** [comment]
if you're using epsilon noise prediction and no offset noise you could apply min SNR gamma and it will converge sooner, but i'm not sure your goals whether you're looking for complete sampling of the 10 epochs. that's a lot of data to consume.

you could possibly resize the inputs to a base resolution of 512px and still have good results with faster training. but there's not much we can do. if cost is the issue, you might be able to get away with a greater number of A6000 GPUs and possibly have a better result.

if you're using all square images, you can torch compile the unet using inductor. if you have aspect buckets though, it'll recompile on each new resolution.
