### ISSUE TITLE
remove login to hf in configure.py

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#933]
A simple request. Reason is that hf is currently not easily accessable in certain countries.

**Comment by bghira** [comment]
unfortunately the script is really designed for the lowest common denominator where the vast majority have a requirement to login to HF Hub. is there a way to set it to HF Mirror for ZH? maybe using os envs.

**Comment by bghira** [comment]
@sayakpaul any way to do like HF_INFERENCE_API_ENDPOINT but HF_HUB_ADDRESS="https://hf-mirror.com" ?

**Comment by bghira** [comment]
@zhuliyi0 actually maybe just `HF_ENDPOINT=https://hf-mirror.com python configure.py`

**Comment by zhuliyi0** [comment]
nice it works! Thanks. Closing this now.

**Comment by bghira** [comment]
thanks. i update the docs to hint this.
