### ISSUE TITLE
.ipynb_checkpoints folder crashes training

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#94]
Jupiter Notebook may auto-create this cache folder inside datset folder, it may contain images and caption files. Better to exclude this folder.

**Comment by zhuliyi0** [comment]
for now I just use this to delete all trash before run:

`find . -type d -name ".ipynb_checkpoints" -exec rm -r {} \;`

**Comment by bghira** [comment]
what is the crash trace?

**Comment by bghira** [comment]
i've added a simple workaround to the startup scripts. set `PROTECT_JUPYTER_FOLDERS` to any value if you wish to handle it yourself. i didn't want to add a list of arbitrary things to start excluding, to the dataset manager. this seems like it should be handled outside of the whole process tbh
