### ISSUE TITLE
Training LoRA on top of Civitai-style Flux checkpoint

### ISSUE THREAD

**Issue by PCanavelli** [bghira/SimpleTuner#945]
Hi there,

I am trying to train Flux LoRAs on Civitai community checkpoints. Those are packaged as single .safetensor files, and lack any kind of folder structure and config files.

Predictably, trying to start a training using the same config and command as for [FLUX.1-dev](https://huggingface.co/black-forest-labs/FLUX.1-dev) errors with the following message:

```
OSError: It looks like the config file at '<PATH_TO_CHECKPOINT' is not a valid JSON file.
```

Is there any way to load single-file checkpoints directly using SimpleTuner, or some workaround that can be used to convert those checkpoints into the expected format?

Cheers, and thanks a lot for the work that went into this project

**Comment by bghira** [comment]
those scripts live in the huggingface/diffusers repository as they periodically receive changes/updates and any copies here would probably go out of date
