### ISSUE TITLE
training will not stop when epoch limit reached

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#95]
When epoch number is specified, current code only looks for global step limit, only breaks the step loop at the end of training, and it will execute some extra number of steps equal to the number of epochs.

**Comment by zhuliyi0** [comment]
Super cool project BTW, still messing around paremeters, but the results so far are very promissing, thanks!

**Comment by bghira** [comment]
this is on SDXL or SD 2.x?

**Comment by zhuliyi0** [comment]
all the issues I had was on SDXL, havn't touched 2.x

**Comment by bghira** [comment]
ok so i identified that the style of the sampler might result in just ignoring the end of an epoch until we resume training, at which time it then boosts the epoch number.

i have put #113 for review. can you look?
