### ISSUE TITLE
lr_end does not affect Sine schecule

### ISSUE THREAD

**Issue by zhuliyi0** [bghira/SimpleTuner#954]
It works for polynomial, but not Sine. The lower bound for Sine seems to be half of learning_rate.

**Comment by bghira** [comment]
sine is a custom curve, but if you want to supply a fix i will review it

**Comment by zhuliyi0** [comment]
sine:

```
       lrs = [
            (base_lr - self.eta_min)  # Difference between base_lr and eta_min
            * (math.cos(math.pi + math.pi * self.T_cur / self.T_i) * 0.5 + 0.5)
            + self.eta_min
            for base_lr in self.base_lrs
        ]
```

consine:
```
       lrs = [
            (base_lr - self.eta_min)  # Difference between base_lr and eta_min
            * (-math.cos(math.pi + math.pi * self.T_cur / self.T_i) * 0.5 + 0.5)
            + self.eta_min
            for base_lr in self.base_lrs
        ]
```

Also, the step() function does not calculate T_cur correctly if resumed from checkpoint. I think step is always None so it uses last_epoch. I wasn't able to track down where this is called in the code.

**Comment by zhuliyi0** [comment]
Edited previous reply to add *2 so it has whole cycle within T_i steps.

**Comment by bghira** [comment]
05a3c370

**Comment by zhuliyi0** [comment]
cheers

**Comment by bghira** [comment]
not precisely but you can just make it `--pretrained_model_name_or_path` arg
