### ISSUE TITLE
Using num_train_epochs without max_train_steps: Division by zero

### ISSUE THREAD

**Issue by missEldgard** [bghira/SimpleTuner#960]
I have created a default configuration using configure.py, and set the limit to epoch instead of steps so I have:

    "--num_train_epochs": "30",
    "--max_train_steps": 0,
    
However, I get this error:

    pct_remaining = 1 - (current_step - int(num_warmup_steps)) / decay_steps
    ZeroDivisionError: division by zero

Which is due to this code relying on num train steps probably ?:

            decay_steps = int(num_training_steps) - int(num_warmup_steps)
            pct_remaining = 1 - (current_step - int(num_warmup_steps)) / decay_steps

**Comment by bghira** [comment]
yeah you probably should use just steps, it ultimately makes more sense for training dynamics in the end

**Comment by missEldgard** [comment]
I find way easier to track the amount of epoch to track how many times my training has seen my whole dataset. This way the training length doesn't change when tweaking batch size for example. But yeah I switched to steps in the meantime.

**Comment by bghira** [comment]
but ultimately the training length should change for different batch sizes - this happens because the learning rate dynamics shift, as well, requiring higher learning rate. can't really keep the same settings between batch size shift due to this.
