### ISSUE TITLE
Can this be used on windows 11?

### ISSUE THREAD

**Issue by Vigilence** [bghira/SimpleTuner#989]
Can this be used on windows 11?

**Comment by bghira** [comment]
nope

**Comment by DaveGravel** [comment]
It can work on windows 11 but you need to make some modifications in the code, and here I use Git Bash for execute the script.

![3a0dbcda-0b80-417c-b55e-43e049cef2d0](https://github.com/user-attachments/assets/3429bd66-2ad1-4b44-897e-b7b3123e09b8)
![d4568475-50f2-4a89-8e08-a6d8f75ce66b](https://github.com/user-attachments/assets/d405cc2e-13e3-45af-87b5-de067a04c177)

**Comment by bghira** [comment]
yes, but it is not supported. i don't have any desire or capability to fix windows errors. it's recommended to use Linux for ML.
