### ISSUE TITLE
train batch size params in config.json does not work

### ISSUE THREAD

**Issue by LianShuaiLong** [bghira/SimpleTuner#993]
i have change the train batchsize in the following way:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/fd41779c-7f57-4be7-bf41-b2608ad6af19">

but training parameters is still 8:
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/ccb3b558-c136-4b68-811b-cc85819d3802">

**Comment by bghira** [comment]
default is 4 so this is on your side somewhere. please remember to provide **the actual config files**  when reporting issues.

**Comment by lianshuailong0715** [comment]
the config.json is exactly the actual config file,my friend,

**Comment by bghira** [comment]
`grep -r -i train_batch_size config/`
