### ISSUE TITLE
No matter how to modify the parameters, it won't work on the 24G RTX 4090(CUDA out of memory)

### ISSUE THREAD

**Issue by haoli-zbdbc** [bghira/SimpleTuner#996]
My profile is as follows：
`
{
    "--resume_from_checkpoint": "latest",
    "--data_backend_config": "config/multidatabackend.json",
    "--aspect_bucket_rounding": 2,
    "--seed": 42,
    "--minimum_image_size": 0,
    "--disable_benchmark": false,
    "--output_dir": "output/models",
    "--max_train_steps": 5000,
    "--num_train_epochs": 0,
    "--checkpointing_steps": 500,
    "--checkpoints_total_limit": 5,
    "--tracker_project_name": "full-training",
    "--tracker_run_name": "simpletuner-full",
    "--report_to": "wandb",
    "--model_type": "full",
    "--pretrained_model_name_or_path": "stabilityai/stable-diffusion-xl-base-1.0",
    "--model_family": "sdxl",
    "--train_batch_size": 1,
    "--gradient_checkpointing": "true",
    "--caption_dropout_probability": 0.1,
    "--resolution_type": "pixel_area",
    "--resolution": "512",
    "--validation_seed": 42,
    "--validation_steps": 500,
    "--validation_resolution": "512x512",
    "--validation_guidance": 4.2,
    "--validation_guidance_rescale": "0.0",
    "--validation_num_inference_steps": "30",
    "--validation_prompt": "celebration,christmas,poster",
    "--mixed_precision": "bf16",
    "--optimizer": "adamw_bf16",
    "--learning_rate": "8e-7",
    "--lr_scheduler": "polynomial",
    "--lr_warmup_steps": "500",
    "--base_model_precision": "int8-quanto",
    "--validation_torch_compile": "false"
}
`
I've set the picture resolution to 512; And batchsize is 1, but there is still a problem:torch.cuda.OutOfMemoryError: CUDA out of memory.

**Comment by haoli-zbdbc** [comment]
I also tried DeepSpeed, but it still doesn't work, the configuration is as follows:
`
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 1
  zero3_init_flag: false
  zero_stage: 1
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
`

**Comment by mhirki** [comment]
You can try adding `"--quantize_via": "cpu"` if you're on the main branch. If that's not working, you need to provide more details where exactly out of memory is happening.

**Comment by bghira** [comment]
uh yeah its never going to fit the whole model in 24g for full tuning probably even with deepspeed. kohya does so with a number of tricks thay i will never implement because its not worthwhile. use lycoris instead and quantise the model.

**Comment by bghira** [comment]
i mis-read earlier and defaulted to thinking you were trying to full-finetune Flux. SDXL should definitely run on a 24G system. the quantisation isn't done during a full finetune.  maybe resolution_type=area and resolution=512 and then it's 512 megapixels?
